# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_pricing_card_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featurepermission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when record was created",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="featurepermission",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when record was last updated",
                verbose_name="Updated at",
            ),
        ),
    ]
