# Generated by Django 5.2.12 on 2026-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0006_upgrade_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what this feature provides",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what this feature provides",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="description_fa",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what this feature provides",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="description_tr",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what this feature provides",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what this feature provides",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="name_ar",
            field=models.CharField(
                help_text="Human-readable display name for the feature",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="name_en",
            field=models.CharField(
                help_text="Human-readable display name for the feature",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="name_fa",
            field=models.CharField(
                help_text="Human-readable display name for the feature",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="name_tr",
            field=models.CharField(
                help_text="Human-readable display name for the feature",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="name_uk",
            field=models.CharField(
                help_text="Human-readable display name for the feature",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the plan and its features",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the plan and its features",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_fa",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the plan and its features",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_tr",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the plan and its features",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the plan and its features",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_ar",
            field=models.CharField(
                help_text="Display name of the plan (e.g., Starter, Professional)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_en",
            field=models.CharField(
                help_text="Display name of the plan (e.g., Starter, Professional)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_fa",
            field=models.CharField(
                help_text="Display name of the plan (e.g., Starter, Professional)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_tr",
            field=models.CharField(
                help_text="Display name of the plan (e.g., Starter, Professional)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_uk",
            field=models.CharField(
                help_text="Display name of the plan (e.g., Starter, Professional)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
    ]
