# Generated by Django 5.2.12 on 2026-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="name_ar",
            field=models.CharField(
                help_text="Name of the inventory item",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="name_en",
            field=models.CharField(
                help_text="Name of the inventory item",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="name_fa",
            field=models.CharField(
                help_text="Name of the inventory item",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="name_tr",
            field=models.CharField(
                help_text="Name of the inventory item",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="name_uk",
            field=models.CharField(
                help_text="Name of the inventory item",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="Recipe description or preparation instructions",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Recipe description or preparation instructions",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description_fa",
            field=models.TextField(
                blank=True,
                help_text="Recipe description or preparation instructions",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description_tr",
            field=models.TextField(
                blank=True,
                help_text="Recipe description or preparation instructions",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Recipe description or preparation instructions",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="name_ar",
            field=models.CharField(
                help_text="Recipe name", max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="name_en",
            field=models.CharField(
                help_text="Recipe name", max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="name_fa",
            field=models.CharField(
                help_text="Recipe name", max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="name_tr",
            field=models.CharField(
                help_text="Recipe name", max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="name_uk",
            field=models.CharField(
                help_text="Recipe name", max_length=255, null=True, verbose_name="Name"
            ),
        ),
    ]
