# Generated by Django 5.2.12 on 2026-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="Campaign description",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Campaign description",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="description_fa",
            field=models.TextField(
                blank=True,
                help_text="Campaign description",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="description_tr",
            field=models.TextField(
                blank=True,
                help_text="Campaign description",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Campaign description",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="name_ar",
            field=models.CharField(
                help_text="Campaign name",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="name_en",
            field=models.CharField(
                help_text="Campaign name",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="name_fa",
            field=models.CharField(
                help_text="Campaign name",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="name_tr",
            field=models.CharField(
                help_text="Campaign name",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="name_uk",
            field=models.CharField(
                help_text="Campaign name",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
    ]
