"""
Dashboard models for E-Menum admin mainboard.

Models:
- DashboardInsight: AI/rule-based insights displayed on dashboard
- UserPreference: Per-user settings (pinned items, preferences)

Critical Rules:
- expires_at past → is_active=False (enforced in save())
- Soft delete pattern: deleted_at timestamp
"""

import uuid

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.core.models import SoftDeleteManager, SoftDeleteMixin, TimeStampedMixin


class InsightType(models.TextChoices):
    """Insight severity/type classification."""
    WARNING = 'warning', _('Warning')
    OPPORTUNITY = 'opportunity', _('Opportunity')
    INFO = 'info', _('Info')
    SUCCESS = 'success', _('Success')


class DashboardInsight(TimeStampedMixin, SoftDeleteMixin, models.Model):
    """
    Dashboard insight cards generated by Celery tasks.

    Each insight represents an actionable piece of information:
    churn risk warnings, growth opportunities, system alerts, etc.

    Attributes:
        type: Severity classification (warning/opportunity/info/success)
        title: Short headline for the insight
        body: Detailed description text
        action_label: CTA button text (e.g., 'View Organizations')
        action_url: URL the action button links to
        metric_value: Numeric value to highlight (e.g., count of at-risk orgs)
        metric_label: Label for the metric (e.g., 'organizations')
        priority: Sort order (higher = more important, shown first)
        is_active: Whether insight is currently displayed
        expires_at: Auto-deactivation timestamp

    Rules:
        - If expires_at is in the past, is_active is set to False on save()
        - Priority determines display order (DESC)
        - Max 5 active insights shown on dashboard
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        verbose_name=_('ID'),
    )

    type = models.CharField(
        max_length=20,
        choices=InsightType.choices,
        default=InsightType.INFO,
        db_index=True,
        verbose_name=_('Type'),
        help_text=_('Insight severity/category'),
    )

    title = models.CharField(
        max_length=255,
        verbose_name=_('Title'),
        help_text=_('Short headline for the insight'),
    )

    body = models.TextField(
        verbose_name=_('Body'),
        help_text=_('Detailed description text'),
    )

    action_label = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name=_('Action label'),
        help_text=_('CTA button text'),
    )

    action_url = models.CharField(
        max_length=500,
        blank=True,
        null=True,
        verbose_name=_('Action URL'),
        help_text=_('URL the action button links to'),
    )

    metric_value = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        null=True,
        blank=True,
        verbose_name=_('Metric value'),
        help_text=_('Numeric value to highlight'),
    )

    metric_label = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name=_('Metric label'),
        help_text=_('Label for the metric value'),
    )

    priority = models.IntegerField(
        default=0,
        db_index=True,
        verbose_name=_('Priority'),
        help_text=_('Higher = more important, shown first'),
    )

    is_active = models.BooleanField(
        default=True,
        db_index=True,
        verbose_name=_('Is active'),
        help_text=_('Whether insight is currently displayed'),
    )

    expires_at = models.DateTimeField(
        null=True,
        blank=True,
        db_index=True,
        verbose_name=_('Expires at'),
        help_text=_('Auto-deactivation timestamp'),
    )

    # Managers
    objects = SoftDeleteManager()
    all_objects = models.Manager()

    class Meta:
        db_table = 'dashboard_insights'
        verbose_name = _('Dashboard Insight')
        verbose_name_plural = _('Dashboard Insights')
        ordering = ['-priority', '-created_at']
        indexes = [
            models.Index(
                fields=['is_active', 'expires_at', '-priority'],
                name='di_active_expires_priority_idx',
            ),
            models.Index(
                fields=['deleted_at'],
                name='di_deleted_idx',
            ),
        ]

    def __str__(self):
        return f"[{self.type}] {self.title}"

    def save(self, *args, **kwargs):
        """Auto-deactivate expired insights on save."""
        if self.expires_at and self.expires_at < timezone.now():
            self.is_active = False
        super().save(*args, **kwargs)


class UserPreference(TimeStampedMixin, models.Model):
    """
    Per-user preferences for sidebar pins, recent visits, etc.

    Stores arbitrary JSON data keyed by a string key.
    Used for:
    - sidebar_pins: list of pinned admin URLs
    - recent_pages: list of recently visited admin URLs
    - dashboard_range: preferred date range for dashboard

    Attributes:
        user: FK to auth user
        key: Preference key (e.g., 'sidebar_pins')
        value: JSON value (flexible structure per key)
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        verbose_name=_('ID'),
    )

    user = models.ForeignKey(
        'core.User',
        on_delete=models.CASCADE,
        related_name='dashboard_preferences',
        verbose_name=_('User'),
    )

    key = models.CharField(
        max_length=100,
        verbose_name=_('Key'),
        help_text=_('Preference key (e.g., sidebar_pins)'),
    )

    value = models.JSONField(
        default=dict,
        verbose_name=_('Value'),
        help_text=_('JSON preference data'),
    )

    class Meta:
        db_table = 'dashboard_user_preferences'
        verbose_name = _('User Preference')
        verbose_name_plural = _('User Preferences')
        unique_together = [['user', 'key']]

    def __str__(self):
        return f"{self.user} - {self.key}"
