# Generated by Django (manually created)

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when record was soft-deleted (null = active)",
                        null=True,
                        verbose_name="Deleted at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Customer's display name",
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Customer's email address (unique per organization)",
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Customer's phone number",
                        max_length=20,
                        null=True,
                        verbose_name="Phone",
                    ),
                ),
                (
                    "avatar",
                    models.URLField(
                        blank=True,
                        help_text="URL to customer's profile image",
                        max_length=500,
                        null=True,
                        verbose_name="Avatar URL",
                    ),
                ),
                (
                    "language_preference",
                    models.CharField(
                        default="tr",
                        help_text="Preferred language code (e.g., 'tr', 'en')",
                        max_length=10,
                        verbose_name="Language preference",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("QR_SCAN", "QR Scan"),
                            ("WEB", "Website"),
                            ("APP", "Mobile App"),
                            ("STAFF", "Staff Entry"),
                            ("IMPORT", "Import"),
                            ("REFERRAL", "Referral"),
                        ],
                        default="QR_SCAN",
                        help_text="How the customer was acquired",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Staff notes about the customer",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Customer preferences and settings (JSON)",
                        verbose_name="Settings",
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of orders placed",
                        verbose_name="Total orders",
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount spent (denormalized)",
                        max_digits=12,
                        verbose_name="Total spent",
                    ),
                ),
                (
                    "loyalty_points_balance",
                    models.IntegerField(
                        default=0,
                        help_text="Current loyalty points balance",
                        verbose_name="Loyalty points balance",
                    ),
                ),
                (
                    "first_visit_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time of first visit",
                        null=True,
                        verbose_name="First visit at",
                    ),
                ),
                (
                    "last_visit_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time of most recent visit",
                        null=True,
                        verbose_name="Last visit at",
                    ),
                ),
                (
                    "marketing_consent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether customer consented to receive marketing communications",
                        verbose_name="Marketing consent",
                    ),
                ),
                (
                    "marketing_consent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When marketing consent was given",
                        null=True,
                        verbose_name="Marketing consent at",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this customer belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyPoint",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("EARNED", "Earned"),
                            ("REDEEMED", "Redeemed"),
                            ("BONUS", "Bonus"),
                            ("EXPIRED", "Expired"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("REFERRAL", "Referral"),
                        ],
                        help_text="Type of loyalty point transaction",
                        max_length=20,
                        verbose_name="Transaction type",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Number of points (positive for credit, negative for debit)",
                        verbose_name="Points",
                    ),
                ),
                (
                    "balance_after",
                    models.IntegerField(
                        help_text="Customer's points balance after this transaction",
                        verbose_name="Balance after",
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Order associated with this transaction (if applicable)",
                        null=True,
                        verbose_name="Order ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable description of the transaction",
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When these points expire (null = never)",
                        null=True,
                        verbose_name="Expires at",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional transaction data (JSON)",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer this transaction is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_transactions",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this transaction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_points",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty Point",
                "verbose_name_plural": "Loyalty Points",
                "db_table": "loyalty_points",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when record was soft-deleted (null = active)",
                        null=True,
                        verbose_name="Deleted at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Order this feedback is about (if applicable)",
                        null=True,
                        verbose_name="Order ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("SERVICE", "Service"),
                            ("FOOD", "Food"),
                            ("AMBIANCE", "Ambiance"),
                            ("CLEANLINESS", "Cleanliness"),
                            ("VALUE", "Value"),
                            ("OTHER", "Other"),
                        ],
                        default="GENERAL",
                        help_text="Category of feedback",
                        max_length=20,
                        verbose_name="Feedback type",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Rating on a 1-5 scale", verbose_name="Rating"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Customer feedback comment",
                        null=True,
                        verbose_name="Comment",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("REVIEWED", "Reviewed"),
                            ("RESPONDED", "Responded"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Processing status of the feedback",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "staff_response",
                    models.TextField(
                        blank=True,
                        help_text="Response from staff to the feedback",
                        null=True,
                        verbose_name="Staff response",
                    ),
                ),
                (
                    "responded_by_id",
                    models.UUIDField(
                        blank=True,
                        help_text="User who responded to this feedback",
                        null=True,
                        verbose_name="Responded by",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the response was made",
                        null=True,
                        verbose_name="Responded at",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this feedback can be shown publicly",
                        verbose_name="Is public",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (JSON)",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer who gave this feedback (null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this feedback belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
                "db_table": "feedbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerVisit",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visited_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the visit occurred",
                        verbose_name="Visited at",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("QR_SCAN", "QR Scan"),
                            ("ORDER", "Order"),
                            ("CHECK_IN", "Check-in"),
                            ("STAFF", "Staff Entry"),
                        ],
                        default="QR_SCAN",
                        help_text="How the visit was recorded",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "table_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Table where customer was seated (if applicable)",
                        null=True,
                        verbose_name="Table ID",
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Order placed during this visit (if applicable)",
                        null=True,
                        verbose_name="Order ID",
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Device and browser information (JSON)",
                        verbose_name="Device info",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP address",
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Client user agent string",
                        null=True,
                        verbose_name="User agent",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How long the customer stayed (estimated)",
                        null=True,
                        verbose_name="Duration (minutes)",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch where the visit occurred",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_visits",
                        to="core.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who made this visit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this visit belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_visits",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Visit",
                "verbose_name_plural": "Customer Visits",
                "db_table": "customer_visits",
                "ordering": ["-visited_at"],
            },
        ),
        # Add unique_together constraint for Customer
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("organization", "email")},
        ),
        # Add indexes for Customer
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["organization", "deleted_at"], name="customer_org_deleted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["organization", "email"], name="customer_org_email_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["organization", "phone"], name="customer_org_phone_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["organization", "last_visit_at"],
                name="customer_org_lastvisit_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["organization", "total_spent"], name="customer_org_spent_idx"
            ),
        ),
        # Add indexes for CustomerVisit
        migrations.AddIndex(
            model_name="customervisit",
            index=models.Index(
                fields=["organization", "visited_at"], name="visit_org_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customervisit",
            index=models.Index(
                fields=["customer", "visited_at"], name="visit_customer_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customervisit",
            index=models.Index(
                fields=["organization", "branch", "visited_at"],
                name="visit_org_branch_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customervisit",
            index=models.Index(
                fields=["organization", "source"], name="visit_org_source_idx"
            ),
        ),
        # Add indexes for Feedback
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["organization", "status"], name="feedback_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["organization", "deleted_at"], name="feedback_org_deleted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["organization", "rating"], name="feedback_org_rating_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["customer", "created_at"], name="feedback_customer_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["organization", "feedback_type"], name="feedback_org_type_idx"
            ),
        ),
        # Add indexes for LoyaltyPoint
        migrations.AddIndex(
            model_name="loyaltypoint",
            index=models.Index(
                fields=["organization", "customer"], name="loyalty_org_customer_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltypoint",
            index=models.Index(
                fields=["customer", "created_at"], name="loyalty_customer_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltypoint",
            index=models.Index(
                fields=["organization", "transaction_type"], name="loyalty_org_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltypoint",
            index=models.Index(fields=["expires_at"], name="loyalty_expires_idx"),
        ),
    ]
