# Generated by Django 5.2.12 on 2026-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customers",
            "0002_customer_churn_risk_score_customer_last_visit_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="comment_ar",
            field=models.TextField(
                blank=True,
                help_text="Customer feedback comment",
                null=True,
                verbose_name="Comment",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="comment_en",
            field=models.TextField(
                blank=True,
                help_text="Customer feedback comment",
                null=True,
                verbose_name="Comment",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="comment_fa",
            field=models.TextField(
                blank=True,
                help_text="Customer feedback comment",
                null=True,
                verbose_name="Comment",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="comment_tr",
            field=models.TextField(
                blank=True,
                help_text="Customer feedback comment",
                null=True,
                verbose_name="Comment",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="comment_uk",
            field=models.TextField(
                blank=True,
                help_text="Customer feedback comment",
                null=True,
                verbose_name="Comment",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="staff_response_ar",
            field=models.TextField(
                blank=True,
                help_text="Response from staff to the feedback",
                null=True,
                verbose_name="Staff response",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="staff_response_en",
            field=models.TextField(
                blank=True,
                help_text="Response from staff to the feedback",
                null=True,
                verbose_name="Staff response",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="staff_response_fa",
            field=models.TextField(
                blank=True,
                help_text="Response from staff to the feedback",
                null=True,
                verbose_name="Staff response",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="staff_response_tr",
            field=models.TextField(
                blank=True,
                help_text="Response from staff to the feedback",
                null=True,
                verbose_name="Staff response",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="staff_response_uk",
            field=models.TextField(
                blank=True,
                help_text="Response from staff to the feedback",
                null=True,
                verbose_name="Staff response",
            ),
        ),
    ]
