"""
Advanced Export Service for the Reporting module.

Provides enhanced export capabilities beyond the basic ExportService:
    - White-label PDF with organization branding (logo, colors, fonts)
    - BI tool format stubs (Power BI, Tableau)
    - Custom multi-section report builder

Usage:
    from apps.reporting.services.advanced_export_service import AdvancedExportService

    service = AdvancedExportService()

    # White-label PDF
    pdf_bytes = service.export_white_label_pdf(
        report_data=execution.result_data,
        branding={
            'logo_url': 'https://example.com/logo.png',
            'primary_color': '#2563EB',
            'company_name': 'Cafe Istanbul',
            'font_family': 'Helvetica',
        },
    )

    # BI tool export
    pbix_bytes = service.export_to_bi_format(report_data, bi_tool='powerbi')

    # Custom multi-section report
    report = service.build_custom_report(
        org_id=org.id,
        sections=[
            {'type': 'revenue_summary', 'parameters': {'period': 'MONTHLY'}},
            {'type': 'top_products', 'parameters': {'limit': 10}},
            {'type': 'customer_trends', 'parameters': {'days': 30}},
        ],
        parameters={'title': 'Monthly Business Review'},
    )

Critical Rules:
    - EVERY query MUST filter by organization_id (multi-tenant isolation)
"""

import io
import json
import logging
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, List, Optional

from django.utils import timezone

logger = logging.getLogger(__name__)


class AdvancedExportService:
    """
    Advanced export capabilities for the reporting module.

    Extends basic export with branding, BI tool formats, and
    custom multi-section report building.
    """

    # ─────────────────────────────────────────────────────────
    # WHITE-LABEL PDF EXPORT
    # ─────────────────────────────────────────────────────────

    def export_white_label_pdf(
        self,
        report_data: dict,
        branding: Optional[Dict[str, Any]] = None,
    ) -> bytes:
        """
        Generate a white-label PDF with organization branding.

        Creates a professional PDF report that includes the organization's
        logo, brand colors, and custom fonts.

        Args:
            report_data: The report result data
            branding: Branding configuration:
                - logo_url (str): URL to organization logo
                - primary_color (str): Hex color code (e.g., '#2563EB')
                - secondary_color (str): Hex color code
                - company_name (str): Organization display name
                - font_family (str): Font family name
                - footer_text (str): Custom footer text
                - header_text (str): Custom header text

        Returns:
            bytes: PDF file content
        """
        try:
            from reportlab.lib import colors
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
            from reportlab.lib.units import cm, mm
            from reportlab.platypus import (
                Image,
                Paragraph,
                SimpleDocTemplate,
                Spacer,
                Table,
                TableStyle,
            )
        except ImportError:
            logger.error(
                'reportlab is required for PDF export. '
                'Install with: pip install reportlab'
            )
            raise ImportError('reportlab is required for white-label PDF export')

        branding = branding or {}
        primary_color = branding.get('primary_color', '#2563EB')
        secondary_color = branding.get('secondary_color', '#1E40AF')
        company_name = branding.get('company_name', 'E-Menum')
        font_family = branding.get('font_family', 'Helvetica')
        footer_text = branding.get('footer_text', f'Generated by {company_name}')
        header_text = branding.get('header_text', '')

        # Convert hex colors to reportlab colors
        primary_rl = colors.HexColor(primary_color)
        secondary_rl = colors.HexColor(secondary_color)

        output = io.BytesIO()
        doc = SimpleDocTemplate(
            output,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2.5 * cm,
            bottomMargin=2 * cm,
        )

        styles = getSampleStyleSheet()
        elements = []

        # ── Logo / Company Header ──
        if header_text:
            header_style = ParagraphStyle(
                'BrandHeader',
                parent=styles['Normal'],
                fontSize=10,
                textColor=colors.grey,
            )
            elements.append(Paragraph(header_text, header_style))
            elements.append(Spacer(1, 4))

        company_style = ParagraphStyle(
            'CompanyName',
            parent=styles['Title'],
            fontSize=20,
            textColor=primary_rl,
            fontName=font_family,
            spaceAfter=4,
        )
        elements.append(Paragraph(company_name, company_style))

        # ── Report Title ──
        title = report_data.get('title', 'Report')
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontSize=16,
            textColor=secondary_rl,
            fontName=font_family,
            spaceAfter=8,
        )
        elements.append(Paragraph(title, title_style))

        # ── Generation Date ──
        date_style = ParagraphStyle(
            'DateLine',
            parent=styles['Normal'],
            fontSize=9,
            textColor=colors.grey,
        )
        generated_at = timezone.now().strftime('%Y-%m-%d %H:%M')
        elements.append(Paragraph(f'Generated: {generated_at}', date_style))
        elements.append(Spacer(1, 16))

        # ── Divider Line ──
        divider_table = Table(
            [['']],
            colWidths=[16 * cm],
            rowHeights=[2],
        )
        divider_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), primary_rl),
            ('LINEBELOW', (0, 0), (-1, -1), 0, primary_rl),
        ]))
        elements.append(divider_table)
        elements.append(Spacer(1, 12))

        # ── Summary Section ──
        summary = report_data.get('summary', {})
        if summary:
            summary_title = ParagraphStyle(
                'SummaryTitle',
                parent=styles['Heading2'],
                textColor=primary_rl,
            )
            elements.append(Paragraph('Summary', summary_title))

            summary_data = [
                [str(k), str(self._format_value(v))]
                for k, v in summary.items()
            ]
            if summary_data:
                t = Table(summary_data, colWidths=[8 * cm, 8 * cm])
                t.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (0, -1), f'{font_family}-Bold'
                     if font_family == 'Helvetica' else font_family),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5E7EB')),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                    ('TOPPADDING', (0, 0), (-1, -1), 6),
                    ('ROWBACKGROUNDS', (0, 0), (-1, -1),
                     [colors.white, colors.HexColor('#F9FAFB')]),
                ]))
                elements.append(t)
                elements.append(Spacer(1, 16))

        # ── Data Table ──
        rows = self._extract_rows(report_data)
        if rows:
            data_title = ParagraphStyle(
                'DataTitle',
                parent=styles['Heading2'],
                textColor=primary_rl,
            )
            elements.append(Paragraph('Data', data_title))

            headers = list(rows[0].keys())
            table_data = [headers]
            for row in rows[:100]:
                table_data.append([
                    str(self._format_value(row.get(h, '')))
                    for h in headers
                ])

            num_cols = len(headers)
            col_width = min(16 * cm / max(num_cols, 1), 5 * cm)

            t = Table(table_data, colWidths=[col_width] * num_cols)
            t.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, 0), f'{font_family}-Bold'
                 if font_family == 'Helvetica' else font_family),
                ('BACKGROUND', (0, 0), (-1, 0), primary_rl),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5E7EB')),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1),
                 [colors.white, colors.HexColor('#F9FAFB')]),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
            ]))
            elements.append(t)

            if len(rows) > 100:
                elements.append(Spacer(1, 6))
                elements.append(Paragraph(
                    f'Showing 100 of {len(rows)} rows.',
                    styles['Italic'],
                ))

        # ── Footer ──
        elements.append(Spacer(1, 24))
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=8,
            textColor=colors.grey,
            alignment=1,  # Center
        )
        elements.append(Paragraph(footer_text, footer_style))

        doc.build(elements)
        return output.getvalue()

    # ─────────────────────────────────────────────────────────
    # BI TOOL FORMAT EXPORT
    # ─────────────────────────────────────────────────────────

    def export_to_bi_format(
        self,
        report_data: dict,
        bi_tool: str,
    ) -> bytes:
        """
        Export report data in a BI tool-compatible format.

        Currently provides stubs for Power BI and Tableau formats.
        The actual format implementation requires the respective
        SDK/libraries which are not yet integrated.

        For now, exports data in an intermediate JSON format that
        can be imported by BI tools via their data connectors.

        Args:
            report_data: The report result data
            bi_tool: BI tool name ('powerbi' or 'tableau')

        Returns:
            bytes: File content in the BI tool's format

        Raises:
            ValueError: If the BI tool is not supported
        """
        bi_tool_lower = bi_tool.lower().strip()

        if bi_tool_lower == 'powerbi':
            return self._export_powerbi_format(report_data)
        elif bi_tool_lower == 'tableau':
            return self._export_tableau_format(report_data)
        else:
            raise ValueError(
                f'Unsupported BI tool: {bi_tool}. '
                f'Supported tools: powerbi, tableau'
            )

    def _export_powerbi_format(self, report_data: dict) -> bytes:
        """
        Export data in Power BI compatible JSON format.

        The output is a structured JSON file that can be imported
        into Power BI Desktop using the JSON data connector or
        used with Power BI REST API for dataset creation.

        Args:
            report_data: The report result data

        Returns:
            bytes: JSON content formatted for Power BI import
        """
        rows = self._extract_rows(report_data)

        # Power BI compatible structure
        pbi_data = {
            'name': report_data.get('title', 'E-Menum Report'),
            'tables': [
                {
                    'name': 'ReportData',
                    'columns': [],
                    'rows': [],
                },
            ],
            'metadata': {
                'source': 'E-Menum Analytics Platform',
                'generated_at': timezone.now().isoformat(),
                'format_version': '1.0',
                'bi_tool': 'powerbi',
            },
        }

        if rows:
            # Infer column types
            headers = list(rows[0].keys())
            for header in headers:
                sample = rows[0].get(header)
                col_type = self._infer_bi_type(sample)
                pbi_data['tables'][0]['columns'].append({
                    'name': header,
                    'dataType': col_type,
                })

            # Add rows
            for row in rows:
                pbi_row = {}
                for header in headers:
                    value = row.get(header)
                    pbi_row[header] = self._format_value(value)
                pbi_data['tables'][0]['rows'].append(pbi_row)

        # Add summary as a separate table
        summary = report_data.get('summary', {})
        if summary:
            summary_table = {
                'name': 'Summary',
                'columns': [
                    {'name': 'Metric', 'dataType': 'string'},
                    {'name': 'Value', 'dataType': 'string'},
                ],
                'rows': [
                    {'Metric': str(k), 'Value': str(self._format_value(v))}
                    for k, v in summary.items()
                ],
            }
            pbi_data['tables'].append(summary_table)

        content = json.dumps(pbi_data, indent=2, ensure_ascii=False, default=str)
        return content.encode('utf-8')

    def _export_tableau_format(self, report_data: dict) -> bytes:
        """
        Export data in Tableau compatible JSON/CSV format.

        The output is a structured JSON file that can be imported
        into Tableau Desktop using the JSON file connector.

        Args:
            report_data: The report result data

        Returns:
            bytes: JSON content formatted for Tableau import
        """
        rows = self._extract_rows(report_data)

        tableau_data = {
            'metadata': {
                'source': 'E-Menum Analytics Platform',
                'generated_at': timezone.now().isoformat(),
                'format_version': '1.0',
                'bi_tool': 'tableau',
                'title': report_data.get('title', 'E-Menum Report'),
            },
            'schema': {},
            'data': [],
        }

        if rows:
            # Build schema
            headers = list(rows[0].keys())
            for header in headers:
                sample = rows[0].get(header)
                tableau_data['schema'][header] = {
                    'dataType': self._infer_bi_type(sample),
                    'role': self._infer_tableau_role(header),
                }

            # Add flattened rows
            for row in rows:
                tableau_row = {}
                for header in headers:
                    value = row.get(header)
                    tableau_row[header] = self._format_value(value)
                tableau_data['data'].append(tableau_row)

        content = json.dumps(tableau_data, indent=2, ensure_ascii=False, default=str)
        return content.encode('utf-8')

    # ─────────────────────────────────────────────────────────
    # CUSTOM REPORT BUILDER
    # ─────────────────────────────────────────────────────────

    def build_custom_report(
        self,
        org_id,
        sections: List[Dict[str, Any]],
        parameters: Optional[Dict[str, Any]] = None,
    ) -> dict:
        """
        Build a custom report composed of multiple sections.

        Each section references a report handler type and parameters.
        The builder aggregates results from multiple handlers into
        a single composite report.

        Args:
            org_id: Organization UUID (multi-tenant isolation)
            sections: List of section definitions:
                - type (str): Handler type key or predefined section
                - parameters (dict): Section-specific parameters
                - title (str, optional): Section title
            parameters: Global report parameters:
                - title (str): Overall report title
                - description (str): Report description

        Returns:
            dict: Composite report with:
                - title (str)
                - description (str)
                - generated_at (str)
                - sections (list): Section results
                - summary (dict): Aggregated summary
        """
        from apps.reporting.services.report_engine import ReportEngine

        parameters = parameters or {}
        engine = ReportEngine()

        report = {
            'title': parameters.get('title', 'Custom Report'),
            'description': parameters.get('description', ''),
            'generated_at': timezone.now().isoformat(),
            'sections': [],
            'summary': {},
        }

        for idx, section_def in enumerate(sections):
            section_type = section_def.get('type', '')
            section_params = section_def.get('parameters', {})
            section_title = section_def.get('title', f'Section {idx + 1}')

            section_result = {
                'index': idx,
                'type': section_type,
                'title': section_title,
                'status': 'pending',
                'data': None,
                'error': None,
            }

            try:
                # Try to execute as a registered report handler
                if engine.registry.is_registered(section_type):
                    execution = engine.execute_report(
                        org_id=str(org_id),
                        feature_key=section_type,
                        parameters=section_params,
                    )
                    section_result['data'] = execution.result_data
                    section_result['status'] = 'completed'

                    logger.info(
                        'Custom report section completed: org=%s type=%s',
                        org_id, section_type,
                    )
                else:
                    # Try built-in section types
                    section_data = self._build_builtin_section(
                        org_id=org_id,
                        section_type=section_type,
                        parameters=section_params,
                    )
                    if section_data is not None:
                        section_result['data'] = section_data
                        section_result['status'] = 'completed'
                    else:
                        section_result['status'] = 'skipped'
                        section_result['error'] = (
                            f'Unknown section type: {section_type}'
                        )

            except Exception as exc:
                section_result['status'] = 'failed'
                section_result['error'] = str(exc)
                logger.error(
                    'Custom report section failed: org=%s type=%s error=%s',
                    org_id, section_type, exc,
                )

            report['sections'].append(section_result)

        # Build aggregated summary
        completed_count = sum(
            1 for s in report['sections'] if s['status'] == 'completed'
        )
        failed_count = sum(
            1 for s in report['sections'] if s['status'] == 'failed'
        )
        report['summary'] = {
            'total_sections': len(sections),
            'completed': completed_count,
            'failed': failed_count,
            'skipped': len(sections) - completed_count - failed_count,
        }

        return report

    def _build_builtin_section(
        self,
        org_id,
        section_type: str,
        parameters: dict,
    ) -> Optional[dict]:
        """
        Build a built-in section type that does not require a handler.

        Args:
            org_id: Organization UUID
            section_type: Section type identifier
            parameters: Section parameters

        Returns:
            dict: Section data, or None if type is unknown
        """
        builtin_handlers = {
            'credit_summary': self._build_credit_summary_section,
            'benchmark_comparison': self._build_benchmark_section,
        }

        handler = builtin_handlers.get(section_type)
        if handler:
            return handler(org_id, parameters)
        return None

    @staticmethod
    def _build_credit_summary_section(org_id, parameters: dict) -> dict:
        """Build a credit usage summary section."""
        from apps.reporting.services.credit_service import CreditService

        service = CreditService()
        return service.get_usage_summary(
            org_id=org_id,
            start_date=parameters.get('start_date'),
            end_date=parameters.get('end_date'),
        )

    @staticmethod
    def _build_benchmark_section(org_id, parameters: dict) -> dict:
        """Build a benchmark comparison section."""
        from apps.reporting.services.benchmark_service import BenchmarkService

        service = BenchmarkService()
        metric_name = parameters.get('metric_name', 'daily_revenue')
        period = parameters.get('period', 'MONTHLY')

        return service.compare_org_to_benchmark(
            org_id=org_id,
            metric_name=metric_name,
            period=period,
        )

    # ─────────────────────────────────────────────────────────
    # HELPERS
    # ─────────────────────────────────────────────────────────

    @staticmethod
    def _extract_rows(report_data: dict) -> List[dict]:
        """Extract tabular rows from report data."""
        for key in ('rows', 'data', 'items', 'results', 'products', 'orders'):
            if key in report_data and isinstance(report_data[key], list):
                rows = report_data[key]
                if rows and isinstance(rows[0], dict):
                    return rows
        return []

    @staticmethod
    def _format_value(value: Any) -> Any:
        """Format a value for display in exports."""
        if isinstance(value, Decimal):
            return float(value)
        if isinstance(value, datetime):
            return value.strftime('%Y-%m-%d %H:%M')
        if isinstance(value, (dict, list)):
            return str(value)
        return value

    @staticmethod
    def _infer_bi_type(value: Any) -> str:
        """Infer BI tool data type from a Python value."""
        if isinstance(value, bool):
            return 'boolean'
        if isinstance(value, int):
            return 'int64'
        if isinstance(value, (float, Decimal)):
            return 'double'
        if isinstance(value, datetime):
            return 'dateTime'
        return 'string'

    @staticmethod
    def _infer_tableau_role(field_name: str) -> str:
        """Infer Tableau field role from field name."""
        measure_keywords = [
            'amount', 'total', 'count', 'revenue', 'cost', 'price',
            'quantity', 'avg', 'sum', 'percent', 'rate', 'value',
        ]
        name_lower = field_name.lower()
        if any(kw in name_lower for kw in measure_keywords):
            return 'measure'
        return 'dimension'
