#!/bin/bash

# E-Menum Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 001-create

set -e

echo "========================================"
echo "E-Menum Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
BACKEND_PORT=3000
DATABASE_PORT=5432
REDIS_PORT=6379

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -e "${BLUE}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# Check prerequisites
check_prerequisites() {
    echo -e "\n${BLUE}Checking prerequisites...${NC}"

    # Check Node.js
    if ! command -v node &> /dev/null; then
        echo -e "${RED}Node.js is not installed. Please install Node.js 20+${NC}"
        exit 1
    fi
    NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
    if [ "$NODE_VERSION" -lt 20 ]; then
        echo -e "${YELLOW}Warning: Node.js version should be 20+. Current: $(node -v)${NC}"
    else
        echo -e "${GREEN}Node.js $(node -v) OK${NC}"
    fi

    # Check npm
    if ! command -v npm &> /dev/null; then
        echo -e "${RED}npm is not installed${NC}"
        exit 1
    fi
    echo -e "${GREEN}npm $(npm -v) OK${NC}"

    # Check Docker (optional)
    if command -v docker &> /dev/null; then
        echo -e "${GREEN}Docker available${NC}"
        DOCKER_AVAILABLE=true
    else
        echo -e "${YELLOW}Docker not found - will use local services${NC}"
        DOCKER_AVAILABLE=false
    fi
}

# Start infrastructure services
start_infrastructure() {
    echo -e "\n${BLUE}Starting infrastructure services...${NC}"

    if [ "$DOCKER_AVAILABLE" = true ]; then
        # Start PostgreSQL
        if ! docker ps | grep -q "emenum-postgres"; then
            echo "Starting PostgreSQL container..."
            docker run -d --name emenum-postgres \
                -p $DATABASE_PORT:5432 \
                -e POSTGRES_USER=postgres \
                -e POSTGRES_PASSWORD=password \
                -e POSTGRES_DB=emenum \
                postgres:15 || true
        fi

        # Start Redis
        if ! docker ps | grep -q "emenum-redis"; then
            echo "Starting Redis container..."
            docker run -d --name emenum-redis \
                -p $REDIS_PORT:6379 \
                redis:7 || true
        fi
    else
        echo -e "${YELLOW}Please ensure PostgreSQL and Redis are running locally${NC}"
        echo "PostgreSQL should be on port $DATABASE_PORT"
        echo "Redis should be on port $REDIS_PORT"
    fi

    # Wait for services
    wait_for_service $DATABASE_PORT "PostgreSQL"
    wait_for_service $REDIS_PORT "Redis"
}

# Install dependencies
install_dependencies() {
    echo -e "\n${BLUE}Installing dependencies...${NC}"
    npm install
    echo -e "${GREEN}Dependencies installed${NC}"
}

# Setup database
setup_database() {
    echo -e "\n${BLUE}Setting up database...${NC}"

    # Check if .env exists
    if [ ! -f ".env" ]; then
        if [ -f ".env.example" ]; then
            cp .env.example .env
            echo -e "${YELLOW}Created .env from .env.example - please verify settings${NC}"
        else
            echo -e "${YELLOW}No .env file found - creating minimal config${NC}"
            cat > .env << EOF
NODE_ENV=development
PORT=3000
APP_DOMAIN=e-menum.net
DATABASE_URL=postgresql://postgres:password@localhost:5432/emenum
REDIS_URL=redis://localhost:6379
JWT_SECRET=dev-secret-change-in-production-min-32-chars
JWT_REFRESH_SECRET=dev-refresh-secret-change-in-production
JWT_ACCESS_EXPIRY=15m
JWT_REFRESH_EXPIRY=7d
EOF
        fi
    fi

    # Run Prisma commands
    if [ -f "prisma/schema.prisma" ]; then
        echo "Generating Prisma client..."
        npm run prisma:generate 2>/dev/null || npx prisma generate

        echo "Running database migrations..."
        npm run prisma:migrate 2>/dev/null || npx prisma migrate dev --name init

        echo "Seeding database..."
        npm run prisma:seed 2>/dev/null || npx prisma db seed || true

        echo -e "${GREEN}Database setup complete${NC}"
    else
        echo -e "${YELLOW}Prisma schema not found - skipping database setup${NC}"
    fi
}

# Start development server
start_dev_server() {
    echo -e "\n${BLUE}Starting development server...${NC}"

    if [ -f "package.json" ] && grep -q '"dev"' package.json; then
        npm run dev &
        DEV_PID=$!

        # Wait for server to start
        wait_for_service $BACKEND_PORT "Backend"

        echo -e "${GREEN}Development server started (PID: $DEV_PID)${NC}"
    else
        echo -e "${YELLOW}Dev script not found in package.json${NC}"
    fi
}

# Print summary
print_summary() {
    echo ""
    echo "========================================"
    echo -e "${GREEN}Environment Ready!${NC}"
    echo "========================================"
    echo ""
    echo "Services:"
    echo "  Backend:       http://localhost:$BACKEND_PORT"
    echo "  Admin Panel:   http://localhost:$BACKEND_PORT/admin"
    echo "  API:           http://localhost:$BACKEND_PORT/api/v1"
    echo "  PostgreSQL:    localhost:$DATABASE_PORT"
    echo "  Redis:         localhost:$REDIS_PORT"
    echo ""
    echo "Useful commands:"
    echo "  npm run dev              - Start development server"
    echo "  npm run prisma:studio    - Open Prisma Studio"
    echo "  npm test                 - Run tests"
    echo "  npm run lint             - Run linter"
    echo ""
    echo "Documentation:"
    echo "  CLAUDE.md                - Master reference"
    echo "  CONSTRAINTS.md           - Project constraints"
    echo "  MODULE_SYSTEM.md         - Module architecture"
    echo ""
}

# Main execution
main() {
    check_prerequisites
    start_infrastructure
    install_dependencies
    setup_database
    start_dev_server
    print_summary
}

# Run main function
main "$@"
