# Generated by Django 5.2.12 on 2026-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seo", "0003_trackingintegration_corewebvitalssnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="pseotemplate",
            name="name_ar",
            field=models.CharField(
                help_text="Template name for internal reference",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="pseotemplate",
            name="name_en",
            field=models.CharField(
                help_text="Template name for internal reference",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="pseotemplate",
            name="name_fa",
            field=models.CharField(
                help_text="Template name for internal reference",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="pseotemplate",
            name="name_tr",
            field=models.CharField(
                help_text="Template name for internal reference",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="pseotemplate",
            name="name_uk",
            field=models.CharField(
                help_text="Template name for internal reference",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
    ]
