# Generated by Django 5.2.11 on 2026-02-22 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shift_staffmetric_staffschedule_and_more'),
        ('customers', '0002_customer_churn_risk_score_customer_last_visit_date_and_more'),
        ('orders', '0002_remove_order_order_org_number_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total refund amount', max_digits=10, verbose_name='Refund amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKEAWAY', 'Takeaway'), ('DELIVERY', 'Delivery'), ('ONLINE', 'Online')], db_index=True, default='DINE_IN', help_text='Order type (dine-in, takeaway, delivery)', max_length=20, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft-deleted (null = active)', null=True, verbose_name='Deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount'), ('BUY_X_GET_Y', 'Buy X Get Y'), ('LOYALTY', 'Loyalty'), ('COUPON', 'Coupon'), ('STAFF', 'Staff'), ('HAPPY_HOUR', 'Happy Hour')], db_index=True, help_text='Type of discount applied', max_length=20, verbose_name='Discount type')),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or fixed amount)', max_digits=10, verbose_name='Value')),
                ('applied_amount', models.DecimalField(decimal_places=2, help_text='Actual monetary amount applied to the order', max_digits=10, verbose_name='Applied amount')),
                ('code', models.CharField(blank=True, help_text='Coupon or promo code used', max_length=50, null=True, verbose_name='Code')),
                ('reason', models.TextField(blank=True, help_text='Reason for applying the discount', null=True, verbose_name='Reason')),
                ('applied_by', models.ForeignKey(blank=True, help_text='Staff member who applied this discount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Applied by')),
                ('order', models.ForeignKey(blank=True, help_text='Order this discount is applied to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='orders.order', verbose_name='Order')),
                ('organization', models.ForeignKey(help_text='Organization this discount belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'order_discounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'discount_type'], name='disc_org_type_idx'), models.Index(fields=['organization', 'deleted_at'], name='disc_org_deleted_idx'), models.Index(fields=['organization', 'order'], name='disc_org_order_idx'), models.Index(fields=['organization', 'code'], name='disc_org_code_idx')],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft-deleted (null = active)', null=True, verbose_name='Deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_type', models.CharField(choices=[('FULL', 'Full Refund'), ('PARTIAL', 'Partial Refund'), ('ITEM', 'Item Refund')], db_index=True, help_text='Type of refund (full, partial, or item)', max_length=20, verbose_name='Refund type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund monetary amount', max_digits=10, verbose_name='Amount')),
                ('reason', models.TextField(help_text='Reason for the refund', verbose_name='Reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Current refund status', max_length=20, verbose_name='Status')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when refund was processed', null=True, verbose_name='Processed at')),
                ('order', models.ForeignKey(help_text='Order being refunded', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order', verbose_name='Order')),
                ('order_item', models.ForeignKey(blank=True, help_text='Specific order item being refunded (for item-level refunds)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.orderitem', verbose_name='Order item')),
                ('organization', models.ForeignKey(help_text='Organization this refund belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.organization', verbose_name='Organization')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Staff member who processed this refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Processed by')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'db_table': 'order_refunds',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='refund_org_status_idx'), models.Index(fields=['organization', 'deleted_at'], name='refund_org_deleted_idx'), models.Index(fields=['organization', 'order'], name='refund_org_order_idx'), models.Index(fields=['organization', 'refund_type'], name='refund_org_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft-deleted (null = active)', null=True, verbose_name='Deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(help_text='Name of the guest making the reservation', max_length=200, verbose_name='Guest name')),
                ('guest_phone', models.CharField(help_text='Phone number of the guest', max_length=20, verbose_name='Guest phone')),
                ('guest_count', models.PositiveIntegerField(help_text='Number of guests expected', verbose_name='Guest count')),
                ('reservation_date', models.DateField(help_text='Date of the reservation', verbose_name='Reservation date')),
                ('reservation_time', models.TimeField(help_text='Time of the reservation', verbose_name='Reservation time')),
                ('duration_minutes', models.PositiveIntegerField(default=90, help_text='Expected duration of the reservation in minutes', verbose_name='Duration (minutes)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SEATED', 'Seated'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current reservation status', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the reservation', null=True, verbose_name='Notes')),
                ('customer', models.ForeignKey(blank=True, help_text='Registered customer who made this reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='customers.customer', verbose_name='Customer')),
                ('organization', models.ForeignKey(help_text='Organization this reservation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.organization', verbose_name='Organization')),
                ('table', models.ForeignKey(blank=True, help_text='Table assigned to this reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='orders.table', verbose_name='Table')),
                ('zone', models.ForeignKey(blank=True, help_text='Preferred zone/section for this reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='orders.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'order_reservations',
                'ordering': ['reservation_date', 'reservation_time'],
                'indexes': [models.Index(fields=['organization', 'status'], name='resv_org_status_idx'), models.Index(fields=['organization', 'deleted_at'], name='resv_org_deleted_idx'), models.Index(fields=['organization', 'reservation_date'], name='resv_org_date_idx'), models.Index(fields=['organization', 'reservation_date', 'status'], name='resv_org_date_status_idx'), models.Index(fields=['organization', 'table'], name='resv_org_table_idx'), models.Index(fields=['organization', 'zone'], name='resv_org_zone_idx'), models.Index(fields=['organization', 'guest_phone'], name='resv_org_phone_idx')],
            },
        ),
    ]
