# Generated by Django 5.2.12 on 2026-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_add_media_fk_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the QR code purpose",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the QR code purpose",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="description_fa",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the QR code purpose",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="description_tr",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the QR code purpose",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the QR code purpose",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="name_ar",
            field=models.CharField(
                help_text="Display name for the QR code",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="name_en",
            field=models.CharField(
                help_text="Display name for the QR code",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="name_fa",
            field=models.CharField(
                help_text="Display name for the QR code",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="name_tr",
            field=models.CharField(
                help_text="Display name for the QR code",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="name_uk",
            field=models.CharField(
                help_text="Display name for the QR code",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="name_ar",
            field=models.CharField(
                help_text='Display name/number of the table (e.g., "Table 1", "A-12")',
                max_length=50,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="name_en",
            field=models.CharField(
                help_text='Display name/number of the table (e.g., "Table 1", "A-12")',
                max_length=50,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="name_fa",
            field=models.CharField(
                help_text='Display name/number of the table (e.g., "Table 1", "A-12")',
                max_length=50,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="name_tr",
            field=models.CharField(
                help_text='Display name/number of the table (e.g., "Table 1", "A-12")',
                max_length=50,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="name_uk",
            field=models.CharField(
                help_text='Display name/number of the table (e.g., "Table 1", "A-12")',
                max_length=50,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the zone and its characteristics",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the zone and its characteristics",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="description_fa",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the zone and its characteristics",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="description_tr",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the zone and its characteristics",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the zone and its characteristics",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="name_ar",
            field=models.CharField(
                help_text="Display name of the zone (e.g., Garden, VIP Section)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="name_en",
            field=models.CharField(
                help_text="Display name of the zone (e.g., Garden, VIP Section)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="name_fa",
            field=models.CharField(
                help_text="Display name of the zone (e.g., Garden, VIP Section)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="name_tr",
            field=models.CharField(
                help_text="Display name of the zone (e.g., Garden, VIP Section)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="name_uk",
            field=models.CharField(
                help_text="Display name of the zone (e.g., Garden, VIP Section)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
    ]
