# Generated by Django 5.2.12 on 2026-03-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportexecution",
            name="progress_message",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable progress status, e.g. 'Generating charts…'",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="reportexecution",
            name="progress_percentage",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Execution progress 0-100. Updated periodically by the Celery task.",
            ),
        ),
    ]
