# Generated by Django 5.2.12 on 2026-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_add_media_fk_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="allergen",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the allergen and its sources",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="allergen",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the allergen and its sources",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="allergen",
            name="description_fa",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the allergen and its sources",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="allergen",
            name="description_tr",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the allergen and its sources",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="allergen",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the allergen and its sources",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="allergen",
            name="name_ar",
            field=models.CharField(
                help_text="Display name of the allergen (e.g., Gluten, Nuts, Dairy)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="allergen",
            name="name_en",
            field=models.CharField(
                help_text="Display name of the allergen (e.g., Gluten, Nuts, Dairy)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="allergen",
            name="name_fa",
            field=models.CharField(
                help_text="Display name of the allergen (e.g., Gluten, Nuts, Dairy)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="allergen",
            name="name_tr",
            field=models.CharField(
                help_text="Display name of the allergen (e.g., Gluten, Nuts, Dairy)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="allergen",
            name="name_uk",
            field=models.CharField(
                help_text="Display name of the allergen (e.g., Gluten, Nuts, Dairy)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the category",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the category",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="description_fa",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the category",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="description_tr",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the category",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the category",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ar",
            field=models.CharField(
                help_text="Display name of the category",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                help_text="Display name of the category",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_fa",
            field=models.CharField(
                help_text="Display name of the category",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_tr",
            field=models.CharField(
                help_text="Display name of the category",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_uk",
            field=models.CharField(
                help_text="Display name of the category",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the menu",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the menu",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="description_fa",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the menu",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="description_tr",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the menu",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the menu",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="name_ar",
            field=models.CharField(
                help_text="Display name of the menu",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="name_en",
            field=models.CharField(
                help_text="Display name of the menu",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="name_fa",
            field=models.CharField(
                help_text="Display name of the menu",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="name_tr",
            field=models.CharField(
                help_text="Display name of the menu",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="name_uk",
            field=models.CharField(
                help_text="Display name of the menu",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="Full product description",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Full product description",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_fa",
            field=models.TextField(
                blank=True,
                help_text="Full product description",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_tr",
            field=models.TextField(
                blank=True,
                help_text="Full product description",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Full product description",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ar",
            field=models.CharField(
                help_text="Display name of the product",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                help_text="Display name of the product",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_fa",
            field=models.CharField(
                help_text="Display name of the product",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_tr",
            field=models.CharField(
                help_text="Display name of the product",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_uk",
            field=models.CharField(
                help_text="Display name of the product",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description_ar",
            field=models.CharField(
                blank=True,
                help_text="Brief description for listings (max 100 chars)",
                max_length=100,
                null=True,
                verbose_name="Short description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description_en",
            field=models.CharField(
                blank=True,
                help_text="Brief description for listings (max 100 chars)",
                max_length=100,
                null=True,
                verbose_name="Short description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description_fa",
            field=models.CharField(
                blank=True,
                help_text="Brief description for listings (max 100 chars)",
                max_length=100,
                null=True,
                verbose_name="Short description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description_tr",
            field=models.CharField(
                blank=True,
                help_text="Brief description for listings (max 100 chars)",
                max_length=100,
                null=True,
                verbose_name="Short description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description_uk",
            field=models.CharField(
                blank=True,
                help_text="Brief description for listings (max 100 chars)",
                max_length=100,
                null=True,
                verbose_name="Short description",
            ),
        ),
        migrations.AddField(
            model_name="productmodifier",
            name="name_ar",
            field=models.CharField(
                help_text="Display name of the modifier (e.g., Extra Cheese, No Onion)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="productmodifier",
            name="name_en",
            field=models.CharField(
                help_text="Display name of the modifier (e.g., Extra Cheese, No Onion)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="productmodifier",
            name="name_fa",
            field=models.CharField(
                help_text="Display name of the modifier (e.g., Extra Cheese, No Onion)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="productmodifier",
            name="name_tr",
            field=models.CharField(
                help_text="Display name of the modifier (e.g., Extra Cheese, No Onion)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="productmodifier",
            name="name_uk",
            field=models.CharField(
                help_text="Display name of the modifier (e.g., Extra Cheese, No Onion)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="name_ar",
            field=models.CharField(
                help_text="Display name of the variant (e.g., Small, Large, Regular)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="name_en",
            field=models.CharField(
                help_text="Display name of the variant (e.g., Small, Large, Regular)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="name_fa",
            field=models.CharField(
                help_text="Display name of the variant (e.g., Small, Large, Regular)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="name_tr",
            field=models.CharField(
                help_text="Display name of the variant (e.g., Small, Large, Regular)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="name_uk",
            field=models.CharField(
                help_text="Display name of the variant (e.g., Small, Large, Regular)",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the theme",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the theme",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="description_fa",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the theme",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="description_tr",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the theme",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the theme",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="name_ar",
            field=models.CharField(
                help_text="Display name of the theme",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="name_en",
            field=models.CharField(
                help_text="Display name of the theme",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="name_fa",
            field=models.CharField(
                help_text="Display name of the theme",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="name_tr",
            field=models.CharField(
                help_text="Display name of the theme",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="name_uk",
            field=models.CharField(
                help_text="Display name of the theme",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
    ]
