# Generated by Django 5.2.11 on 2026-02-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branch',
            name='branch_org_slug_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='permission',
            name='permission_resource_action_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='role_name_scope_org_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='rolepermission',
            name='roleperm_role_perm_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='userrole',
            name='userrole_user_role_org_branch_uniq',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('PERMISSION_GRANT', 'Permission Grant'), ('PERMISSION_REVOKE', 'Permission Revoke'), ('ROLE_ASSIGN', 'Role Assign'), ('ROLE_REMOVE', 'Role Remove'), ('INVITE_SENT', 'Invite Sent'), ('INVITE_ACCEPTED', 'Invite Accepted'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('BULK_UPDATE', 'Bulk Update'), ('BULK_DELETE', 'Bulk Delete'), ('SUBSCRIPTION_CREATED', 'Subscription Created'), ('SUBSCRIPTION_UPDATED', 'Subscription Updated'), ('SUBSCRIPTION_CANCELLED', 'Subscription Cancelled'), ('SETTINGS_UPDATED', 'Settings Updated'), ('API_KEY_CREATED', 'API Key Created'), ('API_KEY_REVOKED', 'API Key Revoked')], db_index=True, help_text='Type of action performed', max_length=30, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DELETED', 'Deleted')], db_index=True, default='ACTIVE', help_text='Organization lifecycle status', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('list', 'List'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('manage', 'Manage'), ('publish', 'Publish'), ('export', 'Export'), ('import', 'Import')], help_text='Action type (view, create, update, delete, etc.)', max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INVITED', 'Invited'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', help_text='User account status', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('organization', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('resource', 'action')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'scope', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'organization', 'branch')},
        ),
    ]
