# Generated by Django 5.2.12 on 2026-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_add_media_fk_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the role and its capabilities",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the role and its capabilities",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_fa",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the role and its capabilities",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_tr",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the role and its capabilities",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the role and its capabilities",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="display_name_ar",
            field=models.CharField(
                help_text="Human-readable role name",
                max_length=100,
                null=True,
                verbose_name="Display name",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="display_name_en",
            field=models.CharField(
                help_text="Human-readable role name",
                max_length=100,
                null=True,
                verbose_name="Display name",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="display_name_fa",
            field=models.CharField(
                help_text="Human-readable role name",
                max_length=100,
                null=True,
                verbose_name="Display name",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="display_name_tr",
            field=models.CharField(
                help_text="Human-readable role name",
                max_length=100,
                null=True,
                verbose_name="Display name",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="display_name_uk",
            field=models.CharField(
                help_text="Human-readable role name",
                max_length=100,
                null=True,
                verbose_name="Display name",
            ),
        ),
    ]
