"""
API Views for the Analytics application.

All views are read-only. Analytics data is generated by background tasks
(aggregate_hourly_analytics) and consumed via these endpoints.
"""

import logging

from django_filters import rest_framework as filters
from rest_framework import generics, permissions

from apps.analytics.models import (
    CustomerMetric,
    DashboardMetric,
    ProductPerformance,
    SalesAggregation,
)
from apps.analytics.serializers import (
    CustomerMetricSerializer,
    DashboardMetricSerializer,
    ProductPerformanceSerializer,
    SalesAggregationSerializer,
)

logger = logging.getLogger(__name__)


# =============================================================================
# FILTERS
# =============================================================================


class DashboardMetricFilter(filters.FilterSet):
    metric_type = filters.CharFilter(field_name='metric_type')
    period_type = filters.CharFilter(field_name='period_type')
    date_from = filters.DateFilter(field_name='period_start', lookup_expr='gte')
    date_to = filters.DateFilter(field_name='period_end', lookup_expr='lte')

    class Meta:
        model = DashboardMetric
        fields = ['metric_type', 'period_type']


class SalesAggregationFilter(filters.FilterSet):
    granularity = filters.CharFilter(field_name='granularity')
    date_from = filters.DateFilter(field_name='date', lookup_expr='gte')
    date_to = filters.DateFilter(field_name='date', lookup_expr='lte')

    class Meta:
        model = SalesAggregation
        fields = ['granularity']


class ProductPerformanceFilter(filters.FilterSet):
    period_type = filters.CharFilter(field_name='period_type')
    product = filters.UUIDFilter(field_name='product_id')
    date_from = filters.DateFilter(field_name='period_start', lookup_expr='gte')
    date_to = filters.DateFilter(field_name='period_end', lookup_expr='lte')

    class Meta:
        model = ProductPerformance
        fields = ['period_type', 'product']


class CustomerMetricFilter(filters.FilterSet):
    date_from = filters.DateFilter(field_name='date', lookup_expr='gte')
    date_to = filters.DateFilter(field_name='date', lookup_expr='lte')

    class Meta:
        model = CustomerMetric
        fields = []


# =============================================================================
# MIXINS
# =============================================================================


class TenantAnalyticsMixin:
    """Filter analytics data by the requesting user's organization."""
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        qs = super().get_queryset()
        organization = getattr(self.request, 'organization', None)
        if organization:
            return qs.filter(organization=organization)
        return qs.none()


# =============================================================================
# VIEWS
# =============================================================================


class DashboardMetricListView(TenantAnalyticsMixin, generics.ListAPIView):
    """
    List cached dashboard KPI metrics.

    Filters: metric_type, period_type, date_from, date_to
    """
    queryset = DashboardMetric.objects.all().order_by('-period_start')
    serializer_class = DashboardMetricSerializer
    filterset_class = DashboardMetricFilter


class DashboardMetricDetailView(TenantAnalyticsMixin, generics.RetrieveAPIView):
    """Retrieve a single dashboard metric."""
    queryset = DashboardMetric.objects.all()
    serializer_class = DashboardMetricSerializer


class SalesAggregationListView(TenantAnalyticsMixin, generics.ListAPIView):
    """
    List pre-aggregated sales data.

    Filters: granularity (daily/hourly), date_from, date_to
    """
    queryset = SalesAggregation.objects.all().order_by('-date')
    serializer_class = SalesAggregationSerializer
    filterset_class = SalesAggregationFilter


class ProductPerformanceListView(TenantAnalyticsMixin, generics.ListAPIView):
    """
    List product performance metrics.

    Filters: period_type, product, date_from, date_to
    """
    queryset = ProductPerformance.objects.all().order_by('-revenue')
    serializer_class = ProductPerformanceSerializer
    filterset_class = ProductPerformanceFilter

    def get_queryset(self):
        return super().get_queryset().select_related('product')


class CustomerMetricListView(TenantAnalyticsMixin, generics.ListAPIView):
    """
    List daily customer statistics.

    Filters: date_from, date_to
    """
    queryset = CustomerMetric.objects.all().order_by('-date')
    serializer_class = CustomerMetricSerializer
    filterset_class = CustomerMetricFilter
