# Generated by Django 5.2.11 on 2026-02-24 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardInsight',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft-deleted (null = active)', null=True, verbose_name='Deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('warning', 'Warning'), ('opportunity', 'Opportunity'), ('info', 'Info'), ('success', 'Success')], db_index=True, default='info', help_text='Insight severity/category', max_length=20, verbose_name='Type')),
                ('title', models.CharField(help_text='Short headline for the insight', max_length=255, verbose_name='Title')),
                ('body', models.TextField(help_text='Detailed description text', verbose_name='Body')),
                ('action_label', models.CharField(blank=True, help_text='CTA button text', max_length=100, null=True, verbose_name='Action label')),
                ('action_url', models.CharField(blank=True, help_text='URL the action button links to', max_length=500, null=True, verbose_name='Action URL')),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric value to highlight', max_digits=15, null=True, verbose_name='Metric value')),
                ('metric_label', models.CharField(blank=True, help_text='Label for the metric value', max_length=100, null=True, verbose_name='Metric label')),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='Higher = more important, shown first', verbose_name='Priority')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether insight is currently displayed', verbose_name='Is active')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Auto-deactivation timestamp', null=True, verbose_name='Expires at')),
            ],
            options={
                'verbose_name': 'Dashboard Insight',
                'verbose_name_plural': 'Dashboard Insights',
                'db_table': 'dashboard_insights',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'expires_at', '-priority'], name='di_active_expires_priority_idx'), models.Index(fields=['deleted_at'], name='di_deleted_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Preference key (e.g., sidebar_pins)', max_length=100, verbose_name='Key')),
                ('value', models.JSONField(default=dict, help_text='JSON preference data', verbose_name='Value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'dashboard_user_preferences',
                'unique_together': {('user', 'key')},
            },
        ),
    ]
