# Generated by Django 5.2.11 on 2026-02-23 10:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotWhitelist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bot identifier (e.g., Googlebot, Bingbot)', max_length=100, verbose_name='Name')),
                ('user_agent_pattern', models.CharField(help_text='Regex pattern to match the bot User-Agent string', max_length=300, verbose_name='User-Agent pattern')),
                ('dns_domain', models.CharField(blank=True, help_text='Expected reverse DNS domain (e.g., googlebot.com)', max_length=200, verbose_name='DNS domain')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bot whitelist entry is active', verbose_name='Is active')),
                ('verification_method', models.CharField(choices=[('dns', 'DNS reverse lookup'), ('ip_range', 'IP range'), ('user_agent', 'User-Agent string')], default='dns', help_text='How to verify the bot identity', max_length=20, verbose_name='Verification method')),
                ('ip_ranges', models.JSONField(blank=True, default=list, help_text='CIDR blocks for IP range verification', verbose_name='IP ranges')),
                ('last_verified', models.DateTimeField(blank=True, help_text='When the bot identity was last verified', null=True, verbose_name='Last verified')),
            ],
            options={
                'verbose_name': 'Bot Whitelist',
                'verbose_name_plural': 'Bot Whitelist',
                'db_table': 'shield_bot_whitelist',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft-deleted (null = active)', null=True, verbose_name='Deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('rules', models.JSONField(blank=True, default=list, help_text='List of rule definitions (JSON)', verbose_name='Rules')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('priority', models.IntegerField(default=100, help_text='Lower value = higher priority', verbose_name='Priority')),
                ('action', models.CharField(choices=[('block', 'Block'), ('challenge', 'Challenge'), ('log', 'Log only'), ('throttle', 'Throttle')], default='log', help_text='Action to take when rules match', max_length=20, verbose_name='Action')),
                ('match_count', models.PositiveIntegerField(default=0, help_text='Number of times this rule set has matched', verbose_name='Match count')),
            ],
            options={
                'verbose_name': 'Rule Set',
                'verbose_name_plural': 'Rule Sets',
                'db_table': 'shield_rule_sets',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='IPRiskScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IP address')),
                ('risk_score', models.IntegerField(default=0, help_text='0-100 risk score', verbose_name='Risk score')),
                ('signals', models.JSONField(blank=True, default=dict, help_text='Signal breakdown (e.g., {rate_limit: 30, header_anomaly: 20})', verbose_name='Signals')),
                ('total_requests', models.PositiveIntegerField(default=0, verbose_name='Total requests')),
                ('blocked_requests', models.PositiveIntegerField(default=0, verbose_name='Blocked requests')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='First seen')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Last seen')),
                ('is_whitelisted', models.BooleanField(default=False, verbose_name='Is whitelisted')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='Is blacklisted')),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2, verbose_name='Country code')),
                ('asn', models.CharField(blank=True, help_text='Autonomous System Number and name', max_length=100, verbose_name='ASN')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'IP Risk Score',
                'verbose_name_plural': 'IP Risk Scores',
                'db_table': 'shield_ip_risk_scores',
                'indexes': [models.Index(fields=['risk_score'], name='shield_ip_risk_score_idx'), models.Index(fields=['is_blacklisted'], name='shield_ip_blacklisted_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('path', models.CharField(help_text='Requested URL path', max_length=500, verbose_name='Path')),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10, verbose_name='Method')),
                ('reason', models.CharField(help_text='Why the action was taken (e.g., rate_limit, bot_impersonation)', max_length=50, verbose_name='Reason')),
                ('risk_score', models.IntegerField(default=0, verbose_name='Risk score')),
                ('signals', models.JSONField(blank=True, default=dict, help_text='Signal breakdown at time of action', verbose_name='Signals')),
                ('action_taken', models.CharField(choices=[('blocked', 'Blocked'), ('challenged', 'Challenged'), ('throttled', 'Throttled'), ('logged', 'Logged')], default='logged', max_length=20, verbose_name='Action taken')),
                ('response_code', models.IntegerField(default=200, help_text='HTTP response status code returned', verbose_name='Response code')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='Country code')),
                ('rule', models.ForeignKey(blank=True, help_text='Rule set that triggered this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_logs', to='seo_shield.ruleset', verbose_name='Rule')),
            ],
            options={
                'verbose_name': 'Block Log',
                'verbose_name_plural': 'Block Logs',
                'db_table': 'shield_block_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='shield_log_ip_created_idx'), models.Index(fields=['reason', 'created_at'], name='shield_log_reason_created_idx'), models.Index(fields=['action_taken'], name='shield_log_action_idx')],
            },
        ),
    ]
