#!/bin/bash

# =============================================================================
# E-Menum Django Development Environment Setup
# Generated by Planner Agent - Session 1
# =============================================================================

set -e

echo "========================================"
echo "E-Menum Django - Development Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
PROJECT_ROOT="$(cd "$(dirname "$0")/../../../" && pwd)"
DJANGO_ROOT="${PROJECT_ROOT}/e_menum"
VENV_PATH="${PROJECT_ROOT}/.venv"
PYTHON_VERSION="3.10"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -n "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e " ${RED}FAILED${NC}"
            return 1
        fi
        sleep 1
        echo -n "."
    done
    echo -e " ${GREEN}OK${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo -e "${BLUE}[1/6] Checking Prerequisites${NC}"

# Check Python version
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Python 3 is required but not installed${NC}"
    exit 1
fi

PYTHON_VER=$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
echo "  Python version: ${PYTHON_VER}"

# Check for required tools
for cmd in pip3 psql redis-cli; do
    if command -v $cmd &> /dev/null; then
        echo -e "  $cmd: ${GREEN}found${NC}"
    else
        echo -e "  $cmd: ${YELLOW}not found (optional)${NC}"
    fi
done

# ============================================
# CREATE VIRTUAL ENVIRONMENT
# ============================================

echo ""
echo -e "${BLUE}[2/6] Setting Up Virtual Environment${NC}"

if [ ! -d "$VENV_PATH" ]; then
    echo "  Creating virtual environment at $VENV_PATH"
    python3 -m venv "$VENV_PATH"
else
    echo "  Virtual environment already exists"
fi

# Activate virtual environment
source "$VENV_PATH/bin/activate"
echo -e "  Virtual environment: ${GREEN}activated${NC}"

# Upgrade pip
pip install --upgrade pip --quiet

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo -e "${BLUE}[3/6] Installing Dependencies${NC}"

if [ -f "$DJANGO_ROOT/requirements.txt" ]; then
    echo "  Installing from requirements.txt..."
    pip install -r "$DJANGO_ROOT/requirements.txt" --quiet
    echo -e "  Production dependencies: ${GREEN}installed${NC}"
else
    echo -e "  ${YELLOW}requirements.txt not found - creating project first${NC}"
    # Install base Django dependencies
    pip install Django djangorestframework djangorestframework-simplejwt django-environ psycopg django-filter django-cors-headers celery redis django-guardian --quiet
    echo -e "  Core dependencies: ${GREEN}installed${NC}"
fi

if [ -f "$DJANGO_ROOT/requirements-dev.txt" ]; then
    echo "  Installing development dependencies..."
    pip install -r "$DJANGO_ROOT/requirements-dev.txt" --quiet
    echo -e "  Development dependencies: ${GREEN}installed${NC}"
fi

# ============================================
# CREATE .ENV FILE
# ============================================

echo ""
echo -e "${BLUE}[4/6] Configuring Environment${NC}"

if [ ! -f "$DJANGO_ROOT/.env" ]; then
    if [ -f "$DJANGO_ROOT/.env.example" ]; then
        cp "$DJANGO_ROOT/.env.example" "$DJANGO_ROOT/.env"
        echo -e "  .env file: ${GREEN}created from example${NC}"
    else
        # Create minimal .env file
        cat > "$DJANGO_ROOT/.env" << 'EOF'
# Django Settings
SECRET_KEY=dev-secret-key-change-in-production
DEBUG=True
ALLOWED_HOSTS=localhost,127.0.0.1

# Database
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/emenum

# Redis
REDIS_URL=redis://localhost:6379/0

# JWT Settings
JWT_ACCESS_TOKEN_LIFETIME=15
JWT_REFRESH_TOKEN_LIFETIME=10080

# Celery
CELERY_BROKER_URL=redis://localhost:6379/0
CELERY_RESULT_BACKEND=redis://localhost:6379/0
EOF
        echo -e "  .env file: ${GREEN}created with defaults${NC}"
    fi
else
    echo -e "  .env file: ${GREEN}exists${NC}"
fi

# ============================================
# CHECK SERVICES
# ============================================

echo ""
echo -e "${BLUE}[5/6] Checking External Services${NC}"

# PostgreSQL
if nc -z localhost 5432 2>/dev/null; then
    echo -e "  PostgreSQL (5432): ${GREEN}running${NC}"
else
    echo -e "  PostgreSQL (5432): ${YELLOW}not running${NC}"
    echo "    Start with: docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:15"
fi

# Redis
if nc -z localhost 6379 2>/dev/null; then
    echo -e "  Redis (6379): ${GREEN}running${NC}"
else
    echo -e "  Redis (6379): ${YELLOW}not running${NC}"
    echo "    Start with: docker run -d -p 6379:6379 redis:7"
fi

# ============================================
# RUN DJANGO SETUP
# ============================================

echo ""
echo -e "${BLUE}[6/6] Django Setup${NC}"

if [ -f "$DJANGO_ROOT/manage.py" ]; then
    cd "$DJANGO_ROOT"

    # Run migrations
    echo "  Running migrations..."
    if python manage.py migrate --check 2>/dev/null; then
        echo -e "  Migrations: ${GREEN}up to date${NC}"
    else
        python manage.py migrate
        echo -e "  Migrations: ${GREEN}applied${NC}"
    fi

    # Collect static files (if in production mode)
    if [ "$DEBUG" != "True" ]; then
        python manage.py collectstatic --noinput
        echo -e "  Static files: ${GREEN}collected${NC}"
    fi

    # Run system check
    echo "  Running system check..."
    if python manage.py check 2>/dev/null; then
        echo -e "  System check: ${GREEN}passed${NC}"
    else
        echo -e "  System check: ${YELLOW}warnings found${NC}"
    fi
else
    echo -e "  ${YELLOW}Django project not yet created${NC}"
    echo "  Run Phase 1 subtasks first to create the project structure"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "To activate the virtual environment:"
echo "  source $VENV_PATH/bin/activate"
echo ""
echo "To start Django development server:"
echo "  cd $DJANGO_ROOT && python manage.py runserver 0.0.0.0:8000"
echo ""
echo "To start Celery worker:"
echo "  cd $DJANGO_ROOT && celery -A config worker -l INFO"
echo ""
echo "Service URLs:"
echo "  Django App:   http://localhost:8000"
echo "  Django Admin: http://localhost:8000/admin"
echo "  API Docs:     http://localhost:8000/api/docs"
echo ""
echo "External Services:"
echo "  PostgreSQL:   localhost:5432"
echo "  Redis:        localhost:6379"
echo ""
