"""
Management command to seed additional organizations with menus, categories, and products.

Creates realistic Turkish restaurant data for multiple organizations beyond
the initial Lezzet Sarayi, so the admin panel looks populated.

Usage:
    python manage.py seed_extra_orgs
    python manage.py seed_extra_orgs --clear
"""

import logging
import random
from datetime import timedelta
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.utils import timezone
from django.utils.text import slugify

logger = logging.getLogger(__name__)
User = get_user_model()
now = timezone.now


def rand_past(days_back=90):
    return now() - timedelta(
        days=random.randint(1, days_back), hours=random.randint(0, 23)
    )


# ---------------------------------------------------------------------------
# Organization definitions
# ---------------------------------------------------------------------------
ORGS = [
    {
        "name": "Bosphorus Bistro",
        "slug": "bosphorus-bistro",
        "email": "info@bosphorusbistro.com",
        "phone": "+90 212 445 67 89",
        "owner_email": "mehmet@bosphorusbistro.com",
        "owner_first": "Mehmet",
        "owner_last": "Ozturk",
        "theme": {
            "name_tr": "Okyanus Mavisi",
            "name_en": "Ocean Blue",
            "name_ar": "الأزرق المحيطي",
            "name_fa": "آبی اقیانوسی",
            "name_uk": "Океанський блакитний",
            "description_tr": "Deniz esintili mavi tema",
            "description_en": "Sea-inspired blue theme",
            "description_ar": "سمة زرقاء مستوحاة من البحر",
            "description_fa": "تم آبی الهام گرفته از دریا",
            "description_uk": "Тема синього кольору натхненна морем",
            "primary_color": "#1e40af",
            "secondary_color": "#60a5fa",
            "background_color": "#f8fafc",
            "text_color": "#1e293b",
            "accent_color": "#0ea5e9",
        },
        "menu": {
            "name_tr": "Ana Menu",
            "name_en": "Main Menu",
            "name_ar": "القائمة الرئيسية",
            "name_fa": "منوی اصلی",
            "name_uk": "Головне меню",
            "description_tr": "Bosphorus Bistro ana menusu",
            "description_en": "Bosphorus Bistro main menu",
            "description_ar": "القائمة الرئيسية لمطعم بوسفور بيسترو",
            "description_fa": "منوی اصلی رستوران بسفر بیسترو",
            "description_uk": "Головне меню ресторану Босфор Бістро",
        },
        "categories": [
            {
                "name_tr": "Kahvalti",
                "name_en": "Breakfast",
                "name_ar": "الإفطار",
                "name_fa": "صبحانه",
                "name_uk": "Сніданок",
                "slug": "kahvalti",
                "icon": "ph-sun",
                "products": [
                    {
                        "name_tr": "Serpme Kahvalti",
                        "name_en": "Spread Breakfast",
                        "name_ar": "فطور تركي مشكل",
                        "name_fa": "صبحانه گسترده",
                        "name_uk": "Сніданок-асорті",
                        "desc_tr": "Zengin serpme kahvalti tabagi, peynir cesitleri, zeytin, bal, kaymak",
                        "desc_en": "Rich spread breakfast platter with cheese varieties, olives, honey, cream",
                        "desc_ar": "طبق فطور غني مع أجبان متنوعة، زيتون، عسل، قشطة",
                        "desc_fa": "بشقاب صبحانه غنی با انواع پنیر، زیتون، عسل، سرشیر",
                        "desc_uk": "Багатий сніданок з асортиментом сирів, оливками, медом, вершками",
                        "price": 280,
                        "image": "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400",
                    },
                    {
                        "name_tr": "Menemen",
                        "name_en": "Menemen",
                        "name_ar": "مينيمين",
                        "name_fa": "منمن",
                        "name_uk": "Менемен",
                        "desc_tr": "Geleneksel domates ve biberli menemen",
                        "desc_en": "Traditional tomato and pepper scrambled eggs",
                        "desc_ar": "بيض مخفوق تقليدي بالطماطم والفلفل",
                        "desc_fa": "تخم مرغ به هم زده سنتی با گوجه و فلفل",
                        "desc_uk": "Традиційна яєчня з помідорами та перцем",
                        "price": 75,
                        "image": "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=400",
                    },
                    {
                        "name_tr": "Sucuklu Yumurta",
                        "name_en": "Eggs with Sucuk",
                        "name_ar": "بيض بالسجق",
                        "name_fa": "تخم مرغ با سوجوک",
                        "name_uk": "Яйця з суджуком",
                        "desc_tr": "Kasap sucugu ile sahanda yumurta",
                        "desc_en": "Pan-fried eggs with butcher's sucuk sausage",
                        "desc_ar": "بيض مقلي مع سجق الجزار",
                        "desc_fa": "تخم مرغ سرخ شده با سوسیس سوجوک قصابی",
                        "desc_uk": "Яєчня на сковороді з ковбасою суджук",
                        "price": 85,
                        "image": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400",
                    },
                    {
                        "name_tr": "Acma & Pogaca",
                        "name_en": "Acma & Pogaca Pastries",
                        "name_ar": "آتشما وبوغاتشا",
                        "name_fa": "آچما و پوغاچا",
                        "name_uk": "Ачма та Поґача",
                        "desc_tr": "Taze firinda acma ve peynirli pogaca (4 adet)",
                        "desc_en": "Fresh baked acma and cheese pogaca pastries (4 pcs)",
                        "desc_ar": "آتشما وبوغاتشا بالجبن طازجة من الفرن (4 قطع)",
                        "desc_fa": "آچما و پوغاچای پنیری تازه از فر (4 عدد)",
                        "desc_uk": "Свіжоспечені ачма та поґача з сиром (4 шт)",
                        "price": 55,
                        "image": None,
                    },
                ],
            },
            {
                "name_tr": "Balik & Deniz Urunleri",
                "name_en": "Fish & Seafood",
                "name_ar": "الأسماك والمأكولات البحرية",
                "name_fa": "ماهی و غذاهای دریایی",
                "name_uk": "Риба та морепродукти",
                "slug": "balik-deniz-urunleri",
                "icon": "ph-fish",
                "products": [
                    {
                        "name_tr": "Levrek Izgara",
                        "name_en": "Grilled Sea Bass",
                        "name_ar": "سمك القاروص المشوي",
                        "name_fa": "سی بس کبابی",
                        "name_uk": "Сібас на грилі",
                        "desc_tr": "Taze levrek filetosunun izgarada pisirimi, sebze garnisi",
                        "desc_en": "Fresh sea bass fillet grilled, served with vegetable garnish",
                        "desc_ar": "شريحة سمك القاروص الطازج مشوية مع مقبلات الخضار",
                        "desc_fa": "فیله تازه سی بس کبابی با گارنیش سبزیجات",
                        "desc_uk": "Свіже філе сібаса на грилі з овочевим гарніром",
                        "price": 320,
                        "image": "https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?w=400",
                    },
                    {
                        "name_tr": "Karides Tava",
                        "name_en": "Pan-Fried Shrimp",
                        "name_ar": "جمبري مقلي",
                        "name_fa": "میگو سرخ شده",
                        "name_uk": "Креветки на сковороді",
                        "desc_tr": "Tereyagli karides tava, roka salatasiyla",
                        "desc_en": "Butter-fried shrimp with arugula salad",
                        "desc_ar": "جمبري مقلي بالزبدة مع سلطة الجرجير",
                        "desc_fa": "میگو سرخ شده با کره همراه سالاد روکولا",
                        "desc_uk": "Креветки на маслі з салатом з рукколи",
                        "price": 280,
                        "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400",
                    },
                    {
                        "name_tr": "Kalamar Tava",
                        "name_en": "Fried Calamari",
                        "name_ar": "كالاماري مقلي",
                        "name_fa": "کالاماری سرخ شده",
                        "name_uk": "Смажені кальмари",
                        "desc_tr": "Citir kalamar halkalari, tarator sosla",
                        "desc_en": "Crispy calamari rings with tarator sauce",
                        "desc_ar": "حلقات كالاماري مقرمشة مع صلصة الطحينة",
                        "desc_fa": "حلقه‌های کالاماری ترد با سس تاراتور",
                        "desc_uk": "Хрусткі кільця кальмарів з соусом таратор",
                        "price": 180,
                        "image": "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400",
                    },
                    {
                        "name_tr": "Hamsi Tava",
                        "name_en": "Fried Anchovies",
                        "name_ar": "أنشوجة مقلية",
                        "name_fa": "آنچوی سرخ شده",
                        "name_uk": "Смажені анчоуси",
                        "desc_tr": "Mevsim hamsisi, misir ununda kizartilmis",
                        "desc_en": "Seasonal anchovies, fried in cornmeal",
                        "desc_ar": "أنشوجة موسمية مقلية بدقيق الذرة",
                        "desc_fa": "آنچوی فصلی، سرخ شده با آرد ذرت",
                        "desc_uk": "Сезонні анчоуси, смажені в кукурудзяному борошні",
                        "price": 140,
                        "image": None,
                    },
                    {
                        "name_tr": "Somon Fume",
                        "name_en": "Smoked Salmon",
                        "name_ar": "سلمون مدخن",
                        "name_fa": "سالمون دودی",
                        "name_uk": "Копчений лосось",
                        "desc_tr": "Ince dilimli somon fume, kapari ve krema peynir",
                        "desc_en": "Thinly sliced smoked salmon with capers and cream cheese",
                        "desc_ar": "سلمون مدخن شرائح رقيقة مع الكبر والجبن الكريمي",
                        "desc_fa": "سالمون دودی برش نازک با کبر و پنیر خامه‌ای",
                        "desc_uk": "Тонко нарізаний копчений лосось з каперсами та вершковим сиром",
                        "price": 195,
                        "image": None,
                    },
                ],
            },
            {
                "name_tr": "Salatalar",
                "name_en": "Salads",
                "name_ar": "السلطات",
                "name_fa": "سالادها",
                "name_uk": "Салати",
                "slug": "salatalar",
                "icon": "ph-leaf",
                "products": [
                    {
                        "name_tr": "Sezar Salata",
                        "name_en": "Caesar Salad",
                        "name_ar": "سلطة سيزر",
                        "name_fa": "سالاد سزار",
                        "name_uk": "Салат Цезар",
                        "desc_tr": "Romaine marulu, parmesan, kruton, sezar sosu",
                        "desc_en": "Romaine lettuce, parmesan, croutons, Caesar dressing",
                        "desc_ar": "خس روماني، بارميزان، خبز محمص، صلصة سيزر",
                        "desc_fa": "کاهو رومی، پارمزان، کروتون، سس سزار",
                        "desc_uk": "Салат ромен, пармезан, крутони, соус Цезар",
                        "price": 110,
                        "image": "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400",
                    },
                    {
                        "name_tr": "Bosphorus Salata",
                        "name_en": "Bosphorus Salad",
                        "name_ar": "سلطة البوسفور",
                        "name_fa": "سالاد بسفر",
                        "name_uk": "Салат Босфор",
                        "desc_tr": "Akdeniz yesillik, nar eksisi, ceviz",
                        "desc_en": "Mediterranean greens, pomegranate molasses, walnuts",
                        "desc_ar": "خضار متوسطية، دبس الرمان، جوز",
                        "desc_fa": "سبزیجات مدیترانه‌ای، رب انار، گردو",
                        "desc_uk": "Середземноморська зелень, гранатовий соус, волоські горіхи",
                        "price": 95,
                        "image": None,
                    },
                    {
                        "name_tr": "Ahtapot Salatasi",
                        "name_en": "Octopus Salad",
                        "name_ar": "سلطة الأخطبوط",
                        "name_fa": "سالاد اختاپوس",
                        "name_uk": "Салат з восьминога",
                        "desc_tr": "Haslama ahtapot, zeytin yagi, limon",
                        "desc_en": "Boiled octopus, olive oil, lemon",
                        "desc_ar": "أخطبوط مسلوق، زيت زيتون، ليمون",
                        "desc_fa": "اختاپوس آب‌پز، روغن زیتون، لیمو",
                        "desc_uk": "Варений восьминіг, оливкова олія, лимон",
                        "price": 195,
                        "image": None,
                    },
                ],
            },
            {
                "name_tr": "Ana Yemekler",
                "name_en": "Main Courses",
                "name_ar": "الأطباق الرئيسية",
                "name_fa": "غذاهای اصلی",
                "name_uk": "Основні страви",
                "slug": "ana-yemekler",
                "icon": "ph-cooking-pot",
                "products": [
                    {
                        "name_tr": "Kuzu Tandir",
                        "name_en": "Slow-Roasted Lamb",
                        "name_ar": "لحم غنم تنور",
                        "name_fa": "بره تنوری",
                        "name_uk": "Баранина тандирна",
                        "desc_tr": "Firinlenmis kuzu tandir, pilav ve salata",
                        "desc_en": "Slow-roasted lamb tandir with rice and salad",
                        "desc_ar": "لحم غنم مشوي في التنور مع أرز وسلطة",
                        "desc_fa": "بره تنوری با پلو و سالاد",
                        "desc_uk": "Баранина тандирна з рисом та салатом",
                        "price": 350,
                        "image": "https://images.unsplash.com/photo-1544025162-d76694265947?w=400",
                    },
                    {
                        "name_tr": "Tas Kebabi",
                        "name_en": "Tas Kebab",
                        "name_ar": "كباب طاس",
                        "name_fa": "کباب تاس",
                        "name_uk": "Таш кебаб",
                        "desc_tr": "Yumusacik dana eti, patates ve havuc",
                        "desc_en": "Tender beef stew with potatoes and carrots",
                        "desc_ar": "لحم بقري طري مع بطاطا وجزر",
                        "desc_fa": "خورشت گوشت گاو لطیف با سیب‌زمینی و هویج",
                        "desc_uk": "Ніжна яловичина з картоплею та морквою",
                        "price": 220,
                        "image": None,
                    },
                    {
                        "name_tr": "Hunkar Begendi",
                        "name_en": "Sultan's Delight",
                        "name_ar": "هنكار بيكندي",
                        "name_fa": "هونکار بیندی",
                        "name_uk": "Хюнкар бегенді",
                        "desc_tr": "Kuzu kusleme, patlicanli besamel sos",
                        "desc_en": "Braised lamb on smoky eggplant bechamel",
                        "desc_ar": "لحم غنم مطهو مع صلصة الباذنجان المدخن",
                        "desc_fa": "خورشت بره با سس بشامل بادمجان دودی",
                        "desc_uk": "Тушкована баранина на баклажановому бешамелі",
                        "price": 260,
                        "image": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400",
                    },
                    {
                        "name_tr": "Islak Hamburger",
                        "name_en": "Wet Burger",
                        "name_ar": "همبرغر مبلل",
                        "name_fa": "همبرگر خیس",
                        "name_uk": "Мокрий бургер",
                        "desc_tr": "Istanbul usulu islak hamburger",
                        "desc_en": "Istanbul-style steamed wet burger",
                        "desc_ar": "همبرغر إسطنبولي مبلل على البخار",
                        "desc_fa": "همبرگر خیس به سبک استانبول",
                        "desc_uk": "Мокрий бургер по-стамбульськи",
                        "price": 95,
                        "image": None,
                    },
                ],
            },
            {
                "name_tr": "Tatlilar",
                "name_en": "Desserts",
                "name_ar": "الحلويات",
                "name_fa": "دسرها",
                "name_uk": "Десерти",
                "slug": "tatlilar-bb",
                "icon": "ph-cake",
                "products": [
                    {
                        "name_tr": "San Sebastian Cheesecake",
                        "name_en": "San Sebastian Cheesecake",
                        "name_ar": "تشيز كيك سان سيباستيان",
                        "name_fa": "چیزکیک سن سباستین",
                        "name_uk": "Чизкейк Сан-Себастьян",
                        "desc_tr": "Ozel tarif, yanmis cheesecake",
                        "desc_en": "Special recipe, burnt Basque cheesecake",
                        "desc_ar": "وصفة خاصة، تشيز كيك باسكي محروق",
                        "desc_fa": "دستور ویژه، چیزکیک باسک سوخته",
                        "desc_uk": "Особливий рецепт, баскський чизкейк",
                        "price": 120,
                        "image": "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400",
                    },
                    {
                        "name_tr": "Sutlac",
                        "name_en": "Baked Rice Pudding",
                        "name_ar": "أرز بالحليب مخبوز",
                        "name_fa": "شیربرنج پخته",
                        "name_uk": "Запечений рисовий пудинг",
                        "desc_tr": "Firinlanmis geleneksel sutlac",
                        "desc_en": "Oven-baked traditional rice pudding",
                        "desc_ar": "أرز بالحليب تقليدي مخبوز في الفرن",
                        "desc_fa": "شیربرنج سنتی پخته شده در فر",
                        "desc_uk": "Традиційний рисовий пудинг запечений у духовці",
                        "price": 65,
                        "image": None,
                    },
                    {
                        "name_tr": "Kazandibi",
                        "name_en": "Kazandibi",
                        "name_ar": "قازان ديبي",
                        "name_fa": "کازان دیبی",
                        "name_uk": "Казандібі",
                        "desc_tr": "Karamelize sutlu tatli",
                        "desc_en": "Caramelized milk pudding",
                        "desc_ar": "حلوى حليب مكرملة",
                        "desc_fa": "دسر شیری کاراملی",
                        "desc_uk": "Карамелізований молочний десерт",
                        "price": 70,
                        "image": None,
                    },
                ],
            },
            {
                "name_tr": "Icecekler",
                "name_en": "Beverages",
                "name_ar": "المشروبات",
                "name_fa": "نوشیدنی‌ها",
                "name_uk": "Напої",
                "slug": "icecekler-bb",
                "icon": "ph-coffee",
                "products": [
                    {
                        "name_tr": "Turk Cayi",
                        "name_en": "Turkish Tea",
                        "name_ar": "شاي تركي",
                        "name_fa": "چای ترکی",
                        "name_uk": "Турецький чай",
                        "desc_tr": "Geleneksel ince belli bardakta cay",
                        "desc_en": "Traditional tea in a slim-waisted glass",
                        "desc_ar": "شاي تقليدي في كوب رفيع الخصر",
                        "desc_fa": "چای سنتی در لیوان کمرباریک",
                        "desc_uk": "Традиційний чай у склянці з тонкою талією",
                        "price": 20,
                        "image": None,
                    },
                    {
                        "name_tr": "Turk Kahvesi",
                        "name_en": "Turkish Coffee",
                        "name_ar": "قهوة تركية",
                        "name_fa": "قهوه ترکی",
                        "name_uk": "Турецька кава",
                        "desc_tr": "Cezvede pisirilen Turk kahvesi",
                        "desc_en": "Turkish coffee brewed in a cezve pot",
                        "desc_ar": "قهوة تركية محضرة في الركوة",
                        "desc_fa": "قهوه ترکی دم شده در جزوه",
                        "desc_uk": "Турецька кава зварена у джезві",
                        "price": 45,
                        "image": None,
                    },
                    {
                        "name_tr": "Taze Portakal Suyu",
                        "name_en": "Fresh Orange Juice",
                        "name_ar": "عصير برتقال طازج",
                        "name_fa": "آب پرتقال تازه",
                        "name_uk": "Свіжий апельсиновий сік",
                        "desc_tr": "Sikma portakal suyu (300ml)",
                        "desc_en": "Freshly squeezed orange juice (300ml)",
                        "desc_ar": "عصير برتقال طازج معصور (300 مل)",
                        "desc_fa": "آب پرتقال تازه فشرده (300 میلی‌لیتر)",
                        "desc_uk": "Свіжовичавлений апельсиновий сік (300 мл)",
                        "price": 55,
                        "image": None,
                    },
                    {
                        "name_tr": "Ayran",
                        "name_en": "Ayran",
                        "name_ar": "عيران",
                        "name_fa": "دوغ",
                        "name_uk": "Айран",
                        "desc_tr": "Ev yapimi ayran",
                        "desc_en": "Homemade ayran yogurt drink",
                        "desc_ar": "عيران منزلي الصنع",
                        "desc_fa": "دوغ خانگی",
                        "desc_uk": "Домашній айран",
                        "price": 25,
                        "image": None,
                    },
                ],
            },
        ],
    },
    {
        "name": "Cafe Noir",
        "slug": "cafe-noir",
        "email": "hello@cafenoir.com.tr",
        "phone": "+90 216 334 55 66",
        "owner_email": "ayse@cafenoir.com.tr",
        "owner_first": "Ayse",
        "owner_last": "Demir",
        "theme": {
            "name_tr": "Koyu Zarafet",
            "name_en": "Dark Elegance",
            "name_ar": "الأناقة الداكنة",
            "name_fa": "ظرافت تیره",
            "name_uk": "Темна елегантність",
            "description_tr": "Koyu tonlarda zarif tema",
            "description_en": "Elegant dark-toned theme",
            "description_ar": "سمة أنيقة بألوان داكنة",
            "description_fa": "تم ظریف با تن تیره",
            "description_uk": "Елегантна тема темних тонів",
            "primary_color": "#1c1917",
            "secondary_color": "#a16207",
            "background_color": "#fafaf9",
            "text_color": "#1c1917",
            "accent_color": "#d97706",
        },
        "menu": {
            "name_tr": "Kahve Menusu",
            "name_en": "Coffee Menu",
            "name_ar": "قائمة القهوة",
            "name_fa": "منوی قهوه",
            "name_uk": "Меню кави",
            "description_tr": "Cafe Noir kahve ve yiyecek menusu",
            "description_en": "Cafe Noir coffee and food menu",
            "description_ar": "قائمة القهوة والطعام لكافيه نوار",
            "description_fa": "منوی قهوه و غذای کافه نوآر",
            "description_uk": "Меню кави та їжі кафе Нуар",
        },
        "categories": [
            {
                "name_tr": "Espresso Bar",
                "name_en": "Espresso Bar",
                "name_ar": "بار الإسبريسو",
                "name_fa": "اسپرسو بار",
                "name_uk": "Еспресо бар",
                "slug": "espresso-bar",
                "icon": "ph-coffee",
                "products": [
                    {
                        "name_tr": "Espresso",
                        "name_en": "Espresso",
                        "name_ar": "إسبريسو",
                        "name_fa": "اسپرسو",
                        "name_uk": "Еспресо",
                        "desc_tr": "Tek shot, %100 Arabica",
                        "desc_en": "Single shot, 100% Arabica",
                        "desc_ar": "جرعة واحدة، 100% أرابيكا",
                        "desc_fa": "یک شات، 100% عربیکا",
                        "desc_uk": "Один шот, 100% Арабіка",
                        "price": 45,
                        "image": "https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=400",
                    },
                    {
                        "name_tr": "Flat White",
                        "name_en": "Flat White",
                        "name_ar": "فلات وايت",
                        "name_fa": "فلت وایت",
                        "name_uk": "Флет вайт",
                        "desc_tr": "Double shot, ipeksi sut kopu",
                        "desc_en": "Double shot, silky milk foam",
                        "desc_ar": "جرعة مزدوجة، رغوة حليب حريرية",
                        "desc_fa": "دو شات، کف شیر ابریشمی",
                        "desc_uk": "Подвійний шот, шовковиста молочна пінка",
                        "price": 65,
                        "image": "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400",
                    },
                    {
                        "name_tr": "Cortado",
                        "name_en": "Cortado",
                        "name_ar": "كورتادو",
                        "name_fa": "کورتادو",
                        "name_uk": "Кортадо",
                        "desc_tr": "Espresso + esit miktarda sut",
                        "desc_en": "Espresso with equal amount of milk",
                        "desc_ar": "إسبريسو مع كمية متساوية من الحليب",
                        "desc_fa": "اسپرسو با مقدار مساوی شیر",
                        "desc_uk": "Еспресо з рівною кількістю молока",
                        "price": 55,
                        "image": None,
                    },
                    {
                        "name_tr": "Latte",
                        "name_en": "Latte",
                        "name_ar": "لاتيه",
                        "name_fa": "لاته",
                        "name_uk": "Лате",
                        "desc_tr": "Single origin, latte art",
                        "desc_en": "Single origin, latte art",
                        "desc_ar": "حبوب أحادية المصدر، فن اللاتيه",
                        "desc_fa": "تک‌خاستگاه، هنر لاته",
                        "desc_uk": "Сінгл оріджин, латте-арт",
                        "price": 60,
                        "image": "https://images.unsplash.com/photo-1534778101976-62847782c213?w=400",
                    },
                    {
                        "name_tr": "Cappuccino",
                        "name_en": "Cappuccino",
                        "name_ar": "كابتشينو",
                        "name_fa": "کاپوچینو",
                        "name_uk": "Капучіно",
                        "desc_tr": "Klasik italyan cappuccino",
                        "desc_en": "Classic Italian cappuccino",
                        "desc_ar": "كابتشينو إيطالي كلاسيكي",
                        "desc_fa": "کاپوچینوی کلاسیک ایتالیایی",
                        "desc_uk": "Класичне італійське капучіно",
                        "price": 60,
                        "image": None,
                    },
                    {
                        "name_tr": "Americano",
                        "name_en": "Americano",
                        "name_ar": "أمريكانو",
                        "name_fa": "آمریکانو",
                        "name_uk": "Американо",
                        "desc_tr": "Double shot + sicak su",
                        "desc_en": "Double shot + hot water",
                        "desc_ar": "جرعة مزدوجة + ماء ساخن",
                        "desc_fa": "دو شات + آب داغ",
                        "desc_uk": "Подвійний шот + гаряча вода",
                        "price": 50,
                        "image": None,
                    },
                    {
                        "name_tr": "V60 Pour Over",
                        "name_en": "V60 Pour Over",
                        "name_ar": "في 60 بور أوفر",
                        "name_fa": "V60 پور اور",
                        "name_uk": "V60 пуровер",
                        "desc_tr": "El demleme, single origin",
                        "desc_en": "Hand-brewed, single origin",
                        "desc_ar": "تخمير يدوي، حبوب أحادية المصدر",
                        "desc_fa": "دم‌آوری دستی، تک‌خاستگاه",
                        "desc_uk": "Ручне заварювання, сінгл оріджин",
                        "price": 75,
                        "image": None,
                    },
                ],
            },
            {
                "name_tr": "Soguk Kahveler",
                "name_en": "Cold Coffees",
                "name_ar": "القهوة الباردة",
                "name_fa": "قهوه‌های سرد",
                "name_uk": "Холодна кава",
                "slug": "soguk-kahveler",
                "icon": "ph-drop",
                "products": [
                    {
                        "name_tr": "Iced Latte",
                        "name_en": "Iced Latte",
                        "name_ar": "لاتيه مثلج",
                        "name_fa": "لاته یخی",
                        "name_uk": "Айс лате",
                        "desc_tr": "Buz uzerinde espresso + sut",
                        "desc_en": "Espresso over ice + milk",
                        "desc_ar": "إسبريسو على الثلج + حليب",
                        "desc_fa": "اسپرسو روی یخ + شیر",
                        "desc_uk": "Еспресо на льоду + молоко",
                        "price": 70,
                        "image": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400",
                    },
                    {
                        "name_tr": "Cold Brew",
                        "name_en": "Cold Brew",
                        "name_ar": "كولد برو",
                        "name_fa": "کلد برو",
                        "name_uk": "Колд брю",
                        "desc_tr": "24 saat demlenmis soguk kahve",
                        "desc_en": "24-hour steeped cold coffee",
                        "desc_ar": "قهوة باردة منقوعة 24 ساعة",
                        "desc_fa": "قهوه سرد 24 ساعت دم‌کشیده",
                        "desc_uk": "Холодна кава 24-годинного настоювання",
                        "price": 75,
                        "image": None,
                    },
                    {
                        "name_tr": "Frappe",
                        "name_en": "Frappe",
                        "name_ar": "فرابيه",
                        "name_fa": "فراپه",
                        "name_uk": "Фрапе",
                        "desc_tr": "Buzlu calkama kahve",
                        "desc_en": "Iced shaken coffee",
                        "desc_ar": "قهوة مثلجة مخفوقة",
                        "desc_fa": "قهوه یخی شیک شده",
                        "desc_uk": "Крижана збита кава",
                        "price": 65,
                        "image": None,
                    },
                    {
                        "name_tr": "Affogato",
                        "name_en": "Affogato",
                        "name_ar": "أفوغاتو",
                        "name_fa": "آفوگاتو",
                        "name_uk": "Афогато",
                        "desc_tr": "Vanilya dondurmasi + espresso",
                        "desc_en": "Vanilla ice cream + espresso",
                        "desc_ar": "آيس كريم فانيليا + إسبريسو",
                        "desc_fa": "بستنی وانیلی + اسپرسو",
                        "desc_uk": "Ванільне морозиво + еспресо",
                        "price": 80,
                        "image": None,
                    },
                ],
            },
            {
                "name_tr": "Pastane",
                "name_en": "Bakery",
                "name_ar": "المخبز",
                "name_fa": "شیرینی‌پزی",
                "name_uk": "Кондитерська",
                "slug": "pastane",
                "icon": "ph-cake",
                "products": [
                    {
                        "name_tr": "Croissant",
                        "name_en": "Croissant",
                        "name_ar": "كرواسون",
                        "name_fa": "کروسان",
                        "name_uk": "Круасан",
                        "desc_tr": "Taze tereyagli croissant",
                        "desc_en": "Fresh buttery croissant",
                        "desc_ar": "كرواسون طازج بالزبدة",
                        "desc_fa": "کروسان تازه کره‌ای",
                        "desc_uk": "Свіжий маслянистий круасан",
                        "price": 55,
                        "image": "https://images.unsplash.com/photo-1555507036-ab1f4038024a?w=400",
                    },
                    {
                        "name_tr": "Pain au Chocolat",
                        "name_en": "Pain au Chocolat",
                        "name_ar": "بان أو شوكولا",
                        "name_fa": "پن او شکلا",
                        "name_uk": "Пен о шокола",
                        "desc_tr": "Cikolatali fransiz pastasi",
                        "desc_en": "French chocolate pastry",
                        "desc_ar": "معجنات فرنسية بالشوكولاتة",
                        "desc_fa": "شیرینی فرانسوی شکلاتی",
                        "desc_uk": "Французька шоколадна випічка",
                        "price": 60,
                        "image": None,
                    },
                    {
                        "name_tr": "Brownie",
                        "name_en": "Brownie",
                        "name_ar": "براوني",
                        "name_fa": "براونی",
                        "name_uk": "Брауні",
                        "desc_tr": "Yogun cikolatali brownie",
                        "desc_en": "Rich chocolate brownie",
                        "desc_ar": "براوني بالشوكولاتة الغنية",
                        "desc_fa": "براونی شکلاتی غنی",
                        "desc_uk": "Насичений шоколадний брауні",
                        "price": 65,
                        "image": "https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=400",
                    },
                    {
                        "name_tr": "Cookie",
                        "name_en": "Cookie",
                        "name_ar": "كوكيز",
                        "name_fa": "کوکی",
                        "name_uk": "Кукі",
                        "desc_tr": "Cikolatali chip cookie (2 adet)",
                        "desc_en": "Chocolate chip cookie (2 pcs)",
                        "desc_ar": "كوكيز برقائق الشوكولاتة (قطعتان)",
                        "desc_fa": "کوکی با تکه‌های شکلات (2 عدد)",
                        "desc_uk": "Шоколадне печиво (2 шт)",
                        "price": 50,
                        "image": None,
                    },
                    {
                        "name_tr": "Carrot Cake",
                        "name_en": "Carrot Cake",
                        "name_ar": "كيك الجزر",
                        "name_fa": "کیک هویج",
                        "name_uk": "Морквяний торт",
                        "desc_tr": "Havuclu tarcinli pasta",
                        "desc_en": "Carrot and cinnamon cake",
                        "desc_ar": "كيك بالجزر والقرفة",
                        "desc_fa": "کیک هویج و دارچین",
                        "desc_uk": "Морквяний торт з корицею",
                        "price": 75,
                        "image": None,
                    },
                    {
                        "name_tr": "Tiramisu",
                        "name_en": "Tiramisu",
                        "name_ar": "تيراميسو",
                        "name_fa": "تیرامیسو",
                        "name_uk": "Тірамісу",
                        "desc_tr": "Klasik Italyan tiramisu",
                        "desc_en": "Classic Italian tiramisu",
                        "desc_ar": "تيراميسو إيطالي كلاسيكي",
                        "desc_fa": "تیرامیسوی کلاسیک ایتالیایی",
                        "desc_uk": "Класичне італійське тірамісу",
                        "price": 85,
                        "image": None,
                    },
                ],
            },
            {
                "name_tr": "Sandvicler",
                "name_en": "Sandwiches",
                "name_ar": "السندويشات",
                "name_fa": "ساندویچ‌ها",
                "name_uk": "Сандвічі",
                "slug": "sandvicler",
                "icon": "ph-bread",
                "products": [
                    {
                        "name_tr": "Club Sandwich",
                        "name_en": "Club Sandwich",
                        "name_ar": "كلوب ساندويتش",
                        "name_fa": "کلاب ساندویچ",
                        "name_uk": "Клаб сендвіч",
                        "desc_tr": "Tavuk, pastirma, marul, domates, mayonez",
                        "desc_en": "Chicken, pastrami, lettuce, tomato, mayonnaise",
                        "desc_ar": "دجاج، بسطرمة، خس، طماطم، مايونيز",
                        "desc_fa": "مرغ، پاسترما، کاهو، گوجه، مایونز",
                        "desc_uk": "Курка, пастрама, салат, помідор, майонез",
                        "price": 125,
                        "image": "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400",
                    },
                    {
                        "name_tr": "Avocado Toast",
                        "name_en": "Avocado Toast",
                        "name_ar": "توست الأفوكادو",
                        "name_fa": "تست آووکادو",
                        "name_uk": "Тост з авокадо",
                        "desc_tr": "Eksi maya ekmegi, avokado, yumurta",
                        "desc_en": "Sourdough bread, avocado, egg",
                        "desc_ar": "خبز العجين المخمر، أفوكادو، بيض",
                        "desc_fa": "نان خمیرترش، آووکادو، تخم مرغ",
                        "desc_uk": "Хліб на заквасці, авокадо, яйце",
                        "price": 110,
                        "image": "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400",
                    },
                    {
                        "name_tr": "Grilled Cheese",
                        "name_en": "Grilled Cheese",
                        "name_ar": "توست الجبن المشوي",
                        "name_fa": "پنیر گریل شده",
                        "name_uk": "Гарячий сирний тост",
                        "desc_tr": "Karisik peynirli tost",
                        "desc_en": "Mixed cheese grilled toast",
                        "desc_ar": "توست مشوي بالجبن المشكل",
                        "desc_fa": "تست گریل شده با پنیر مخلوط",
                        "desc_uk": "Тост-гриль з сумішшю сирів",
                        "price": 85,
                        "image": None,
                    },
                    {
                        "name_tr": "Tuna Melt",
                        "name_en": "Tuna Melt",
                        "name_ar": "ساندويتش التونة الساخن",
                        "name_fa": "ساندویچ تن ماهی گرم",
                        "name_uk": "Гарячий сендвіч з тунцем",
                        "desc_tr": "Ton balikli sicak sandvic",
                        "desc_en": "Hot tuna sandwich with melted cheese",
                        "desc_ar": "ساندويتش تونة ساخن مع جبن ذائب",
                        "desc_fa": "ساندویچ تن ماهی داغ با پنیر ذوب شده",
                        "desc_uk": "Гарячий сендвіч з тунцем та плавленим сиром",
                        "price": 105,
                        "image": None,
                    },
                ],
            },
        ],
    },
    {
        "name": "Sultan Kebap",
        "slug": "sultan-kebap",
        "email": "info@sultankebap.com.tr",
        "phone": "+90 312 222 33 44",
        "owner_email": "ali@sultankebap.com.tr",
        "owner_first": "Ali",
        "owner_last": "Kaya",
        "theme": {
            "name_tr": "Osmanli Kirmizisi",
            "name_en": "Ottoman Red",
            "name_ar": "الأحمر العثماني",
            "name_fa": "قرمز عثمانی",
            "name_uk": "Османський червоний",
            "description_tr": "Osmanli esintili kirmizi tema",
            "description_en": "Ottoman-inspired red theme",
            "description_ar": "سمة حمراء مستوحاة من العثمانيين",
            "description_fa": "تم قرمز الهام گرفته از عثمانی",
            "description_uk": "Тема червоного кольору натхненна Османською імперією",
            "primary_color": "#991b1b",
            "secondary_color": "#dc2626",
            "background_color": "#fef2f2",
            "text_color": "#1f2937",
            "accent_color": "#b91c1c",
        },
        "menu": {
            "name_tr": "Kebap Menusu",
            "name_en": "Kebab Menu",
            "name_ar": "قائمة الكباب",
            "name_fa": "منوی کباب",
            "name_uk": "Меню кебабів",
            "description_tr": "Sultan Kebap ana menusu",
            "description_en": "Sultan Kebap main menu",
            "description_ar": "القائمة الرئيسية لمطعم سلطان كباب",
            "description_fa": "منوی اصلی رستوران سلطان کباب",
            "description_uk": "Головне меню ресторану Султан Кебаб",
        },
        "categories": [
            {
                "name_tr": "Kebaplar",
                "name_en": "Kebabs",
                "name_ar": "الكباب",
                "name_fa": "کبابها",
                "name_uk": "Кебаби",
                "slug": "kebaplar-sk",
                "icon": "ph-fire",
                "products": [
                    {
                        "name_tr": "Adana Kebap",
                        "name_en": "Adana Kebab",
                        "name_ar": "كباب أضنة",
                        "name_fa": "کباب آدانا",
                        "name_uk": "Кебаб Адана",
                        "desc_tr": "Aci kiyma kebap, mangal atesi",
                        "desc_en": "Spicy minced meat kebab, charcoal grilled",
                        "desc_ar": "كباب لحم مفروم حار على الفحم",
                        "desc_fa": "کباب گوشت چرخ‌کرده تند، کباب شده روی زغال",
                        "desc_uk": "Гострий кебаб з фаршу на мангалі",
                        "price": 185,
                        "image": "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=400",
                    },
                    {
                        "name_tr": "Urfa Kebap",
                        "name_en": "Urfa Kebab",
                        "name_ar": "كباب أورفا",
                        "name_fa": "کباب اورفا",
                        "name_uk": "Кебаб Урфа",
                        "desc_tr": "Acsiz kiyma kebap",
                        "desc_en": "Mild minced meat kebab",
                        "desc_ar": "كباب لحم مفروم غير حار",
                        "desc_fa": "کباب گوشت چرخ‌کرده بدون تندی",
                        "desc_uk": "Негострий кебаб з фаршу",
                        "price": 185,
                        "image": None,
                    },
                    {
                        "name_tr": "Iskender",
                        "name_en": "Iskender Kebab",
                        "name_ar": "إسكندر كباب",
                        "name_fa": "کباب اسکندر",
                        "name_uk": "Іскендер кебаб",
                        "desc_tr": "Pide uzerinde doner, tereyagi, yogurt",
                        "desc_en": "Doner kebab over pide bread with butter and yogurt",
                        "desc_ar": "دونر كباب على خبز البيدة مع زبدة ولبن",
                        "desc_fa": "دونر کباب روی نان پیده با کره و ماست",
                        "desc_uk": "Донер кебаб на хлібі піде з маслом та йогуртом",
                        "price": 220,
                        "image": "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400",
                    },
                    {
                        "name_tr": "Patlican Kebap",
                        "name_en": "Eggplant Kebab",
                        "name_ar": "كباب الباذنجان",
                        "name_fa": "کباب بادمجان",
                        "name_uk": "Кебаб з баклажаном",
                        "desc_tr": "Kozlenmis patlican ile kebap",
                        "desc_en": "Kebab with fire-roasted eggplant",
                        "desc_ar": "كباب مع باذنجان مشوي على النار",
                        "desc_fa": "کباب با بادمجان کبابی",
                        "desc_uk": "Кебаб з баклажаном на вогні",
                        "price": 195,
                        "image": None,
                    },
                    {
                        "name_tr": "Karisik Kebap",
                        "name_en": "Mixed Kebab Platter",
                        "name_ar": "كباب مشكل",
                        "name_fa": "کباب مخلوط",
                        "name_uk": "Асорті кебабів",
                        "desc_tr": "Adana, urfa, tavuk sis, kuzu sis",
                        "desc_en": "Adana, urfa, chicken skewer, lamb skewer",
                        "desc_ar": "أضنة، أورفا، شيش دجاج، شيش لحم غنم",
                        "desc_fa": "آدانا، اورفا، جوجه کباب، کباب بره",
                        "desc_uk": "Адана, урфа, курячий шиш, баранячий шиш",
                        "price": 280,
                        "image": None,
                    },
                    {
                        "name_tr": "Beyti Sarma",
                        "name_en": "Beyti Wrap",
                        "name_ar": "بيتي سارما",
                        "name_fa": "بیتی سارما",
                        "name_uk": "Бейті сарма",
                        "desc_tr": "Lavasa sarili kebap, yogurt sosu",
                        "desc_en": "Kebab wrapped in lavash with yogurt sauce",
                        "desc_ar": "كباب ملفوف بالخبز الرقيق مع صلصة اللبن",
                        "desc_fa": "کباب پیچیده در لواش با سس ماست",
                        "desc_uk": "Кебаб загорнутий у лаваш з йогуртовим соусом",
                        "price": 210,
                        "image": None,
                    },
                ],
            },
            {
                "name_tr": "Pideler",
                "name_en": "Turkish Pides",
                "name_ar": "البيدة التركية",
                "name_fa": "پیده‌ها",
                "name_uk": "Піде",
                "slug": "pideler",
                "icon": "ph-bread",
                "products": [
                    {
                        "name_tr": "Kiymali Pide",
                        "name_en": "Minced Meat Pide",
                        "name_ar": "بيدة باللحم المفروم",
                        "name_fa": "پیده گوشت چرخ‌کرده",
                        "name_uk": "Піде з фаршем",
                        "desc_tr": "Taze firindan kiymali pide",
                        "desc_en": "Fresh from the oven, minced meat pide",
                        "desc_ar": "بيدة باللحم المفروم طازجة من الفرن",
                        "desc_fa": "پیده گوشت چرخ‌کرده تازه از فر",
                        "desc_uk": "Свіжоспечена піде з фаршем",
                        "price": 120,
                        "image": None,
                    },
                    {
                        "name_tr": "Kasarli Pide",
                        "name_en": "Cheese Pide",
                        "name_ar": "بيدة بالجبن",
                        "name_fa": "پیده پنیری",
                        "name_uk": "Піде з сиром",
                        "desc_tr": "Kasar peynirli pide",
                        "desc_en": "Pide with kasar cheese",
                        "desc_ar": "بيدة بجبن القشار",
                        "desc_fa": "پیده با پنیر کاشار",
                        "desc_uk": "Піде з сиром кашар",
                        "price": 100,
                        "image": None,
                    },
                    {
                        "name_tr": "Kusbasi Pide",
                        "name_en": "Diced Meat Pide",
                        "name_ar": "بيدة باللحم المكعب",
                        "name_fa": "پیده گوشت خردشده",
                        "name_uk": "Піде з шматочками м'яса",
                        "desc_tr": "Kusbasi etli pide",
                        "desc_en": "Pide with diced meat",
                        "desc_ar": "بيدة باللحم المقطع مكعبات",
                        "desc_fa": "پیده با گوشت خردشده",
                        "desc_uk": "Піде з нарізаним м'ясом",
                        "price": 145,
                        "image": None,
                    },
                    {
                        "name_tr": "Lahmacun",
                        "name_en": "Lahmacun",
                        "name_ar": "لحم بعجين",
                        "name_fa": "لحماجون",
                        "name_uk": "Лахмаджун",
                        "desc_tr": "Ince hamur, kiymali (3 adet)",
                        "desc_en": "Thin flatbread with minced meat (3 pcs)",
                        "desc_ar": "عجينة رقيقة باللحم المفروم (3 قطع)",
                        "desc_fa": "نان نازک با گوشت چرخ‌کرده (3 عدد)",
                        "desc_uk": "Тонкий хліб з фаршем (3 шт)",
                        "price": 90,
                        "image": None,
                    },
                ],
            },
            {
                "name_tr": "Baslangiclar",
                "name_en": "Starters",
                "name_ar": "المقبلات",
                "name_fa": "پیش‌غذاها",
                "name_uk": "Закуски",
                "slug": "baslangiclar-sk",
                "icon": "ph-bowl-food",
                "products": [
                    {
                        "name_tr": "Mercimek Corbasi",
                        "name_en": "Lentil Soup",
                        "name_ar": "شوربة العدس",
                        "name_fa": "سوپ عدس",
                        "name_uk": "Сочевичний суп",
                        "desc_tr": "Kirmizi mercimek corbasi",
                        "desc_en": "Red lentil soup",
                        "desc_ar": "شوربة العدس الأحمر",
                        "desc_fa": "سوپ عدس قرمز",
                        "desc_uk": "Суп з червоної сочевиці",
                        "price": 50,
                        "image": None,
                    },
                    {
                        "name_tr": "Humus",
                        "name_en": "Hummus",
                        "name_ar": "حمص",
                        "name_fa": "حمص",
                        "name_uk": "Хумус",
                        "desc_tr": "Tahinli nohut ezme",
                        "desc_en": "Chickpea dip with tahini",
                        "desc_ar": "حمص مع الطحينة",
                        "desc_fa": "پوره نخود با ارده",
                        "desc_uk": "Нутова паста з тахіні",
                        "price": 55,
                        "image": None,
                    },
                    {
                        "name_tr": "Piyaz",
                        "name_en": "Piyaz Bean Salad",
                        "name_ar": "بياز",
                        "name_fa": "پیاز سالاد",
                        "name_uk": "Піяз",
                        "desc_tr": "Antep usulu piyaz",
                        "desc_en": "Antep-style white bean salad",
                        "desc_ar": "بياز على طريقة عنتاب",
                        "desc_fa": "سالاد لوبیا سفید به سبک آنتپ",
                        "desc_uk": "Салат з білої квасолі по-антепськи",
                        "price": 45,
                        "image": None,
                    },
                    {
                        "name_tr": "Cacik",
                        "name_en": "Cacik",
                        "name_ar": "جاجيق",
                        "name_fa": "جاجیق",
                        "name_uk": "Джаджик",
                        "desc_tr": "Ev yapimi cacik",
                        "desc_en": "Homemade yogurt with cucumber",
                        "desc_ar": "جاجيق منزلي الصنع",
                        "desc_fa": "جاجیق خانگی",
                        "desc_uk": "Домашній джаджик з огірком",
                        "price": 35,
                        "image": None,
                    },
                    {
                        "name_tr": "Ezme Salata",
                        "name_en": "Spicy Ezme Salad",
                        "name_ar": "سلطة إزمة حارة",
                        "name_fa": "سالاد ازمه تند",
                        "name_uk": "Гострий салат езме",
                        "desc_tr": "Aci ezme",
                        "desc_en": "Spicy chopped salad",
                        "desc_ar": "سلطة مفرومة حارة",
                        "desc_fa": "سالاد خردشده تند",
                        "desc_uk": "Гострий подрібнений салат",
                        "price": 40,
                        "image": None,
                    },
                ],
            },
            {
                "name_tr": "Icecekler",
                "name_en": "Beverages",
                "name_ar": "المشروبات",
                "name_fa": "نوشیدنی‌ها",
                "name_uk": "Напої",
                "slug": "icecekler-sk",
                "icon": "ph-beer-bottle",
                "products": [
                    {
                        "name_tr": "Ayran",
                        "name_en": "Ayran",
                        "name_ar": "عيران",
                        "name_fa": "دوغ",
                        "name_uk": "Айран",
                        "desc_tr": "Ev yapimi ayran",
                        "desc_en": "Homemade ayran yogurt drink",
                        "desc_ar": "عيران منزلي الصنع",
                        "desc_fa": "دوغ خانگی",
                        "desc_uk": "Домашній айран",
                        "price": 20,
                        "image": None,
                    },
                    {
                        "name_tr": "Salgam",
                        "name_en": "Turnip Juice",
                        "name_ar": "عصير اللفت",
                        "name_fa": "آب شلغم",
                        "name_uk": "Сік ріпи",
                        "desc_tr": "Adana salgam suyu",
                        "desc_en": "Adana-style turnip juice",
                        "desc_ar": "عصير اللفت على طريقة أضنة",
                        "desc_fa": "آب شلغم به سبک آدانا",
                        "desc_uk": "Сік ріпи по-аданськи",
                        "price": 25,
                        "image": None,
                    },
                    {
                        "name_tr": "Sira",
                        "name_en": "Grape Must",
                        "name_ar": "شيرة العنب",
                        "name_fa": "شیره انگور",
                        "name_uk": "Виноградне сусло",
                        "desc_tr": "Uzum sirasi",
                        "desc_en": "Traditional grape must drink",
                        "desc_ar": "مشروب شيرة العنب التقليدي",
                        "desc_fa": "نوشیدنی سنتی شیره انگور",
                        "desc_uk": "Традиційний напій з виноградного сусла",
                        "price": 30,
                        "image": None,
                    },
                    {
                        "name_tr": "Turk Cayi",
                        "name_en": "Turkish Tea",
                        "name_ar": "شاي تركي",
                        "name_fa": "چای ترکی",
                        "name_uk": "Турецький чай",
                        "desc_tr": "Bardak cay",
                        "desc_en": "Glass of Turkish tea",
                        "desc_ar": "كوب شاي تركي",
                        "desc_fa": "یک لیوان چای ترکی",
                        "desc_uk": "Склянка турецького чаю",
                        "price": 15,
                        "image": None,
                    },
                ],
            },
        ],
    },
]

# Extra media files for all orgs
MEDIA_FILES = [
    ("hero-banner.jpg", "IMAGE", "image/jpeg", 2456000, 1920, 1080),
    ("logo.png", "IMAGE", "image/png", 45000, 512, 512),
    ("menu-bg.jpg", "IMAGE", "image/jpeg", 1890000, 1920, 1280),
    ("promo-video.mp4", "VIDEO", "video/mp4", 15600000, 1920, 1080),
    ("about-us.jpg", "IMAGE", "image/jpeg", 980000, 1200, 800),
    ("instagram-1.jpg", "IMAGE", "image/jpeg", 456000, 1080, 1080),
    ("instagram-2.jpg", "IMAGE", "image/jpeg", 523000, 1080, 1080),
    ("instagram-3.jpg", "IMAGE", "image/jpeg", 487000, 1080, 1080),
]


class Command(BaseCommand):
    help = "Seed additional organizations with menus, products, media and more"

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear", action="store_true", help="Clear existing extra data first"
        )

    def handle(self, *args, **options):
        from apps.core.models import Organization
        from apps.menu.models import Menu, Category, Product, Theme, Allergen
        from apps.media.models import Media, MediaFolder

        if options["clear"]:
            self.stdout.write("Clearing extra organizations...")
            for org_data in ORGS:
                Organization.objects.filter(slug=org_data["slug"]).delete()
            self.stdout.write(self.style.SUCCESS("Cleared."))

        allergens = list(Allergen.objects.filter(deleted_at__isnull=True))

        for org_data in ORGS:
            # --- Organization ---
            org, created = Organization.objects.get_or_create(
                slug=org_data["slug"],
                defaults={
                    "name": org_data["name"],
                    "email": org_data["email"],
                    "phone": org_data["phone"],
                    "status": "ACTIVE",
                    "settings": {"currency": "TRY", "timezone": "Europe/Istanbul"},
                },
            )
            if created:
                self.stdout.write(f"  Created org: {org.name}")
            else:
                self.stdout.write(f"  Org exists: {org.name}")

            # --- Owner user ---
            owner, _ = User.objects.get_or_create(
                email=org_data["owner_email"],
                defaults={
                    "first_name": org_data["owner_first"],
                    "last_name": org_data["owner_last"],
                    "organization": org,
                    "is_staff": True,
                    "status": "ACTIVE",
                },
            )
            if _:
                owner.set_password("Owner1234!emenum")
                owner.save()
            elif not owner.check_password("Owner1234!emenum"):
                owner.set_password("Owner1234!emenum")
                owner.save(update_fields=["password"])
                self.stdout.write(f"  Password reset: {owner.email}")

            # --- Theme ---
            td = org_data["theme"]
            theme, _ = Theme.objects.get_or_create(
                organization=org,
                slug=slugify(td["name_en"]),
                defaults={
                    "name_tr": td["name_tr"],
                    "name_en": td["name_en"],
                    "name_ar": td["name_ar"],
                    "name_fa": td["name_fa"],
                    "name_uk": td["name_uk"],
                    "description_tr": td["description_tr"],
                    "description_en": td["description_en"],
                    "description_ar": td["description_ar"],
                    "description_fa": td["description_fa"],
                    "description_uk": td["description_uk"],
                    "primary_color": td["primary_color"],
                    "secondary_color": td["secondary_color"],
                    "background_color": td["background_color"],
                    "text_color": td["text_color"],
                    "accent_color": td["accent_color"],
                    "is_default": True,
                    "is_active": True,
                },
            )

            # --- Menu ---
            md = org_data["menu"]
            menu_slug = f"{org_data['slug']}-menu"
            menu, _ = Menu.objects.get_or_create(
                organization=org,
                slug=menu_slug,
                defaults={
                    "name_tr": md["name_tr"],
                    "name_en": md["name_en"],
                    "name_ar": md["name_ar"],
                    "name_fa": md["name_fa"],
                    "name_uk": md["name_uk"],
                    "description_tr": md["description_tr"],
                    "description_en": md["description_en"],
                    "description_ar": md["description_ar"],
                    "description_fa": md["description_fa"],
                    "description_uk": md["description_uk"],
                    "is_published": True,
                    "published_at": rand_past(30),
                    "is_default": True,
                    "theme": theme,
                },
            )
            self.stdout.write(f"    Menu: {menu.name_tr} (slug={menu.slug})")

            # --- Categories & Products ---
            for sort_idx, cat_data in enumerate(org_data["categories"]):
                cat, _ = Category.objects.get_or_create(
                    organization=org,
                    menu=menu,
                    slug=cat_data["slug"],
                    defaults={
                        "name_tr": cat_data["name_tr"],
                        "name_en": cat_data["name_en"],
                        "name_ar": cat_data["name_ar"],
                        "name_fa": cat_data["name_fa"],
                        "name_uk": cat_data["name_uk"],
                        "icon": cat_data["icon"],
                        "is_active": True,
                        "sort_order": sort_idx * 10,
                    },
                )

                for prod_idx, p in enumerate(cat_data["products"]):
                    pslug = slugify(p["name_tr"])[:50]
                    desc_tr = p["desc_tr"]
                    desc_en = p["desc_en"]
                    desc_ar = p["desc_ar"]
                    desc_fa = p["desc_fa"]
                    desc_uk = p["desc_uk"]
                    prod_defaults = {
                        "name_tr": p["name_tr"],
                        "name_en": p["name_en"],
                        "name_ar": p["name_ar"],
                        "name_fa": p["name_fa"],
                        "name_uk": p["name_uk"],
                        "short_description_tr": desc_tr[:100] if desc_tr else "",
                        "short_description_en": desc_en[:100] if desc_en else "",
                        "short_description_ar": desc_ar[:100] if desc_ar else "",
                        "short_description_fa": desc_fa[:100] if desc_fa else "",
                        "short_description_uk": desc_uk[:100] if desc_uk else "",
                        "description_tr": desc_tr,
                        "description_en": desc_en,
                        "description_ar": desc_ar,
                        "description_fa": desc_fa,
                        "description_uk": desc_uk,
                        "base_price": Decimal(str(p["price"])),
                        "currency": "TRY",
                        "is_active": True,
                        "is_available": random.random() > 0.1,
                        "is_featured": random.random() > 0.8,
                        "is_chef_recommended": random.random() > 0.85,
                        "sort_order": prod_idx * 10,
                        "preparation_time": random.choice([5, 10, 15, 20, 25, 30]),
                        "calories": random.randint(100, 900)
                        if random.random() > 0.3
                        else None,
                    }
                    if p["image"]:
                        prod_defaults["image"] = p["image"]

                    product, _ = Product.objects.get_or_create(
                        organization=org,
                        category=cat,
                        slug=pslug,
                        defaults=prod_defaults,
                    )

                    # Add random allergens
                    if allergens and random.random() > 0.5:
                        from apps.menu.models import ProductAllergen

                        for allergen in random.sample(
                            allergens, min(random.randint(1, 3), len(allergens))
                        ):
                            ProductAllergen.objects.get_or_create(
                                product=product,
                                allergen=allergen,
                                defaults={
                                    "severity": random.choice(
                                        ["contains", "may_contain", "traces"]
                                    )
                                },
                            )

            # --- Media Folders ---
            root_folder, _ = MediaFolder.objects.get_or_create(
                organization=org,
                slug=f"{org_data['slug']}-media",
                defaults={
                    "name": f"{org_data['name']} Media",
                    "is_public": True,
                },
            )

            products_folder, _ = MediaFolder.objects.get_or_create(
                organization=org,
                slug=f"{org_data['slug']}-products",
                defaults={
                    "name": "Product Images",
                    "parent": root_folder,
                    "is_public": True,
                },
            )

            branding_folder, _ = MediaFolder.objects.get_or_create(
                organization=org,
                slug=f"{org_data['slug']}-branding",
                defaults={
                    "name": "Branding",
                    "parent": root_folder,
                    "is_public": True,
                },
            )

            # --- Media Files ---
            for fname, mtype, mime, fsize, w, h in MEDIA_FILES:
                Media.objects.get_or_create(
                    organization=org,
                    name=f"{org_data['name']} - {fname}",
                    defaults={
                        "original_filename": fname,
                        "media_type": mtype,
                        "mime_type": mime,
                        "file_size": fsize,
                        "width": w,
                        "height": h,
                        "status": "READY",
                        "storage": "LOCAL",
                        "folder": branding_folder
                        if "logo" in fname
                        else products_folder,
                        "uploaded_by": owner,
                        "is_public": True,
                        "file_path": f"media/{org_data['slug']}/{fname}",
                        "url": f"/media/{org_data['slug']}/{fname}",
                    },
                )

            self.stdout.write(self.style.SUCCESS(f"  ✓ {org.name}: done"))

        # Also add more media to existing Lezzet Sarayi
        try:
            lezzet = Organization.objects.get(slug="lezzet-sarayi")
            lezzet_owner = User.objects.filter(
                organization=lezzet, is_staff=True
            ).first()
            if lezzet_owner:
                root, _ = MediaFolder.objects.get_or_create(
                    organization=lezzet,
                    slug="lezzet-root",
                    defaults={"name": "Lezzet Sarayi Media", "is_public": True},
                )
                for fname, mtype, mime, fsize, w, h in MEDIA_FILES[:5]:
                    Media.objects.get_or_create(
                        organization=lezzet,
                        name=f"Lezzet Sarayi - {fname}",
                        defaults={
                            "original_filename": fname,
                            "media_type": mtype,
                            "mime_type": mime,
                            "file_size": fsize,
                            "width": w,
                            "height": h,
                            "status": "READY",
                            "storage": "LOCAL",
                            "folder": root,
                            "uploaded_by": lezzet_owner,
                            "is_public": True,
                            "file_path": f"media/lezzet-sarayi/{fname}",
                            "url": f"/media/lezzet-sarayi/{fname}",
                        },
                    )
                self.stdout.write(
                    self.style.SUCCESS("  ✓ Lezzet Sarayi: extra media added")
                )
        except Organization.DoesNotExist:
            pass

        self.stdout.write(self.style.SUCCESS("\n✅ All extra organizations seeded!"))
