# Generated by Django (manually created)

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft-deleted (null = active)', null=True, verbose_name='Deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER', 'Order'), ('SYSTEM', 'System'), ('PROMOTION', 'Promotion'), ('PAYMENT', 'Payment'), ('FEEDBACK', 'Feedback'), ('SECURITY', 'Security'), ('GENERAL', 'General')], db_index=True, default='GENERAL', help_text='Category of the notification', max_length=20, verbose_name='Notification type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current delivery/read status of the notification', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', help_text='Priority level for ordering and urgency', max_length=10, verbose_name='Priority')),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('PUSH', 'Push'), ('EMAIL', 'Email'), ('SMS', 'SMS')], default='IN_APP', help_text='Delivery channel for the notification', max_length=10, verbose_name='Channel')),
                ('title', models.CharField(help_text='Short title or subject for the notification', max_length=255, verbose_name='Title')),
                ('message', models.TextField(help_text='Full notification message content', verbose_name='Message')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional context data (order_id, urls, etc.)', verbose_name='Data')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read/viewed by the user', null=True, verbose_name='Read at')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, help_text='When the notification was sent to the delivery channel', null=True, verbose_name='Sent at')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the notification was confirmed delivered', null=True, verbose_name='Delivered at')),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='Optional scheduled delivery time (null for immediate)', null=True, verbose_name='Scheduled for')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Optional expiration time after which notification is hidden', null=True, verbose_name='Expires at')),
                ('action_url', models.URLField(blank=True, help_text='Optional URL for click-through action', max_length=500, null=True, verbose_name='Action URL')),
                ('image_url', models.URLField(blank=True, help_text='Optional image URL for rich notifications', max_length=500, null=True, verbose_name='Image URL')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for tracking and analytics', verbose_name='Metadata')),
                ('organization', models.ForeignKey(help_text='Organization this notification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.organization', verbose_name='Organization')),
                ('user', models.ForeignKey(help_text='User who is the recipient of this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        # Add indexes for Notification
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'user', 'status'], name='notif_org_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'status', 'deleted_at'], name='notif_org_status_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status', 'created_at'], name='notif_user_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='notif_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'notification_type'], name='notif_org_type_idx'),
        ),
    ]
