# Generated by Django 5.2.12 on 2026-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message_ar",
            field=models.TextField(
                help_text="Full notification message content",
                null=True,
                verbose_name="Message",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_en",
            field=models.TextField(
                help_text="Full notification message content",
                null=True,
                verbose_name="Message",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_fa",
            field=models.TextField(
                help_text="Full notification message content",
                null=True,
                verbose_name="Message",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_tr",
            field=models.TextField(
                help_text="Full notification message content",
                null=True,
                verbose_name="Message",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_uk",
            field=models.TextField(
                help_text="Full notification message content",
                null=True,
                verbose_name="Message",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_ar",
            field=models.CharField(
                help_text="Short title or subject for the notification",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_en",
            field=models.CharField(
                help_text="Short title or subject for the notification",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_fa",
            field=models.CharField(
                help_text="Short title or subject for the notification",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_tr",
            field=models.CharField(
                help_text="Short title or subject for the notification",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_uk",
            field=models.CharField(
                help_text="Short title or subject for the notification",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
    ]
