# Generated by Django 5.2.11 on 2026-02-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_blogpost_companystat_companyvalue_faq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='kategori'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='kategori'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category_fa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='kategori'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='kategori'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='kategori'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ar',
            field=models.TextField(help_text='HTML icerik desteklenir', null=True, verbose_name='icerik'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(help_text='HTML icerik desteklenir', null=True, verbose_name='icerik'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_fa',
            field=models.TextField(help_text='HTML icerik desteklenir', null=True, verbose_name='icerik'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_tr',
            field=models.TextField(help_text='HTML icerik desteklenir', null=True, verbose_name='icerik'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_uk',
            field=models.TextField(help_text='HTML icerik desteklenir', null=True, verbose_name='icerik'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_ar',
            field=models.TextField(blank=True, help_text='Kart onizlemesinde gosterilir', null=True, verbose_name='ozet'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(blank=True, help_text='Kart onizlemesinde gosterilir', null=True, verbose_name='ozet'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_fa',
            field=models.TextField(blank=True, help_text='Kart onizlemesinde gosterilir', null=True, verbose_name='ozet'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_tr',
            field=models.TextField(blank=True, help_text='Kart onizlemesinde gosterilir', null=True, verbose_name='ozet'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_uk',
            field=models.TextField(blank=True, help_text='Kart onizlemesinde gosterilir', null=True, verbose_name='ozet'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_ar',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='meta aciklama'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='meta aciklama'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_fa',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='meta aciklama'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='meta aciklama'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_uk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='meta aciklama'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ar',
            field=models.CharField(max_length=300, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_tr',
            field=models.CharField(max_length=300, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='companystat',
            name='label_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='companystat',
            name='label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='companystat',
            name='label_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='companystat',
            name='label_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='companystat',
            name='label_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='companystat',
            name='value_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='deger'),
        ),
        migrations.AddField(
            model_name='companystat',
            name='value_en',
            field=models.CharField(max_length=50, null=True, verbose_name='deger'),
        ),
        migrations.AddField(
            model_name='companystat',
            name='value_fa',
            field=models.CharField(max_length=50, null=True, verbose_name='deger'),
        ),
        migrations.AddField(
            model_name='companystat',
            name='value_tr',
            field=models.CharField(max_length=50, null=True, verbose_name='deger'),
        ),
        migrations.AddField(
            model_name='companystat',
            name='value_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='deger'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='description_en',
            field=models.TextField(null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ar',
            field=models.TextField(null=True, verbose_name='cevap'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='cevap'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fa',
            field=models.TextField(null=True, verbose_name='cevap'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_tr',
            field=models.TextField(null=True, verbose_name='cevap'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uk',
            field=models.TextField(null=True, verbose_name='cevap'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ar',
            field=models.CharField(max_length=300, null=True, verbose_name='soru'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=300, null=True, verbose_name='soru'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='soru'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_tr',
            field=models.CharField(max_length=300, null=True, verbose_name='soru'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='soru'),
        ),
        migrations.AddField(
            model_name='featurebullet',
            name='text_ar',
            field=models.CharField(max_length=300, null=True, verbose_name='metin'),
        ),
        migrations.AddField(
            model_name='featurebullet',
            name='text_en',
            field=models.CharField(max_length=300, null=True, verbose_name='metin'),
        ),
        migrations.AddField(
            model_name='featurebullet',
            name='text_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='metin'),
        ),
        migrations.AddField(
            model_name='featurebullet',
            name='text_tr',
            field=models.CharField(max_length=300, null=True, verbose_name='metin'),
        ),
        migrations.AddField(
            model_name='featurebullet',
            name='text_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='metin'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='badge_text_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='badge metni'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='badge_text_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='badge metni'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='badge_text_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='badge metni'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='badge_text_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='badge metni'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='badge_text_uk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='badge metni'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='image_alt_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='gorsel alt metni'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='image_alt_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='gorsel alt metni'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='image_alt_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='gorsel alt metni'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='image_alt_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='gorsel alt metni'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='image_alt_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='gorsel alt metni'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='content_ar',
            field=models.TextField(help_text='HTML icerik desteklenir', null=True, verbose_name='icerik'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='content_en',
            field=models.TextField(help_text='HTML icerik desteklenir', null=True, verbose_name='icerik'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='content_fa',
            field=models.TextField(help_text='HTML icerik desteklenir', null=True, verbose_name='icerik'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='content_tr',
            field=models.TextField(help_text='HTML icerik desteklenir', null=True, verbose_name='icerik'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='content_uk',
            field=models.TextField(help_text='HTML icerik desteklenir', null=True, verbose_name='icerik'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='last_updated_display_ar',
            field=models.CharField(blank=True, help_text='Sayfada gosterilecek tarih metni', max_length=50, null=True, verbose_name='son guncelleme (gorunum)'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='last_updated_display_en',
            field=models.CharField(blank=True, help_text='Sayfada gosterilecek tarih metni', max_length=50, null=True, verbose_name='son guncelleme (gorunum)'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='last_updated_display_fa',
            field=models.CharField(blank=True, help_text='Sayfada gosterilecek tarih metni', max_length=50, null=True, verbose_name='son guncelleme (gorunum)'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='last_updated_display_tr',
            field=models.CharField(blank=True, help_text='Sayfada gosterilecek tarih metni', max_length=50, null=True, verbose_name='son guncelleme (gorunum)'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='last_updated_display_uk',
            field=models.CharField(blank=True, help_text='Sayfada gosterilecek tarih metni', max_length=50, null=True, verbose_name='son guncelleme (gorunum)'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='meta_description_ar',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='meta aciklama'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='meta aciklama'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='meta_description_fa',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='meta aciklama'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='meta_description_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='meta aciklama'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='meta_description_uk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='meta aciklama'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='description_ar',
            field=models.CharField(blank=True, help_text='Dropdown aciklama metni', max_length=200, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='description_en',
            field=models.CharField(blank=True, help_text='Dropdown aciklama metni', max_length=200, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='description_fa',
            field=models.CharField(blank=True, help_text='Dropdown aciklama metni', max_length=200, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='description_tr',
            field=models.CharField(blank=True, help_text='Dropdown aciklama metni', max_length=200, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='description_uk',
            field=models.CharField(blank=True, help_text='Dropdown aciklama metni', max_length=200, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='label_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='label_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='label_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='label_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='badge_text_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='badge metni'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='badge_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='badge metni'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='badge_text_fa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='badge metni'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='badge_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='badge metni'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='badge_text_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='badge metni'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='cta_primary_text_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='birincil CTA'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='cta_primary_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='birincil CTA'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='cta_primary_text_fa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='birincil CTA'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='cta_primary_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='birincil CTA'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='cta_primary_text_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='birincil CTA'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='cta_secondary_text_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ikincil CTA'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='cta_secondary_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ikincil CTA'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='cta_secondary_text_fa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ikincil CTA'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='cta_secondary_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ikincil CTA'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='cta_secondary_text_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ikincil CTA'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='subtitle_ar',
            field=models.TextField(blank=True, null=True, verbose_name='alt baslik'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True, verbose_name='alt baslik'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='subtitle_fa',
            field=models.TextField(blank=True, null=True, verbose_name='alt baslik'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='subtitle_tr',
            field=models.TextField(blank=True, null=True, verbose_name='alt baslik'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='subtitle_uk',
            field=models.TextField(blank=True, null=True, verbose_name='alt baslik'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='baslik'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='trust_text_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='guven metni'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='trust_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='guven metni'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='trust_text_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='guven metni'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='trust_text_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='guven metni'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='trust_text_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='guven metni'),
        ),
        migrations.AddField(
            model_name='plandisplayfeature',
            name='text_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='metin'),
        ),
        migrations.AddField(
            model_name='plandisplayfeature',
            name='text_en',
            field=models.CharField(max_length=200, null=True, verbose_name='metin'),
        ),
        migrations.AddField(
            model_name='plandisplayfeature',
            name='text_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='metin'),
        ),
        migrations.AddField(
            model_name='plandisplayfeature',
            name='text_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='metin'),
        ),
        migrations.AddField(
            model_name='plandisplayfeature',
            name='text_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='metin'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ar',
            field=models.CharField(default='Istanbul, Turkiye', max_length=200, null=True, verbose_name='adres'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(default='Istanbul, Turkiye', max_length=200, null=True, verbose_name='adres'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_fa',
            field=models.CharField(default='Istanbul, Turkiye', max_length=200, null=True, verbose_name='adres'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_tr',
            field=models.CharField(default='Istanbul, Turkiye', max_length=200, null=True, verbose_name='adres'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_uk',
            field=models.CharField(default='Istanbul, Turkiye', max_length=200, null=True, verbose_name='adres'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name_ar',
            field=models.CharField(default='E-Menum', max_length=100, null=True, verbose_name='sirket adi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name_en',
            field=models.CharField(default='E-Menum', max_length=100, null=True, verbose_name='sirket adi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name_fa',
            field=models.CharField(default='E-Menum', max_length=100, null=True, verbose_name='sirket adi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name_tr',
            field=models.CharField(default='E-Menum', max_length=100, null=True, verbose_name='sirket adi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name_uk',
            field=models.CharField(default='E-Menum', max_length=100, null=True, verbose_name='sirket adi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_primary_text_ar',
            field=models.CharField(default='14 Gun Ucretsiz Basla', max_length=100, null=True, verbose_name='birincil CTA metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_primary_text_en',
            field=models.CharField(default='14 Gun Ucretsiz Basla', max_length=100, null=True, verbose_name='birincil CTA metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_primary_text_fa',
            field=models.CharField(default='14 Gun Ucretsiz Basla', max_length=100, null=True, verbose_name='birincil CTA metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_primary_text_tr',
            field=models.CharField(default='14 Gun Ucretsiz Basla', max_length=100, null=True, verbose_name='birincil CTA metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_primary_text_uk',
            field=models.CharField(default='14 Gun Ucretsiz Basla', max_length=100, null=True, verbose_name='birincil CTA metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_secondary_text_ar',
            field=models.CharField(default='Demo Iste', max_length=100, null=True, verbose_name='ikincil CTA metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_secondary_text_en',
            field=models.CharField(default='Demo Iste', max_length=100, null=True, verbose_name='ikincil CTA metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_secondary_text_fa',
            field=models.CharField(default='Demo Iste', max_length=100, null=True, verbose_name='ikincil CTA metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_secondary_text_tr',
            field=models.CharField(default='Demo Iste', max_length=100, null=True, verbose_name='ikincil CTA metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_secondary_text_uk',
            field=models.CharField(default='Demo Iste', max_length=100, null=True, verbose_name='ikincil CTA metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_trust_text_ar',
            field=models.CharField(default='Kredi karti gerekmez · 2 dakikada kurulum', max_length=200, null=True, verbose_name='guven metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_trust_text_en',
            field=models.CharField(default='Kredi karti gerekmez · 2 dakikada kurulum', max_length=200, null=True, verbose_name='guven metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_trust_text_fa',
            field=models.CharField(default='Kredi karti gerekmez · 2 dakikada kurulum', max_length=200, null=True, verbose_name='guven metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_trust_text_tr',
            field=models.CharField(default='Kredi karti gerekmez · 2 dakikada kurulum', max_length=200, null=True, verbose_name='guven metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_trust_text_uk',
            field=models.CharField(default='Kredi karti gerekmez · 2 dakikada kurulum', max_length=200, null=True, verbose_name='guven metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='aciklama'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_ar',
            field=models.CharField(default='QR Menunuz, Isletmenizin Dijital Vitrini', max_length=200, null=True, verbose_name='slogan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(default='QR Menunuz, Isletmenizin Dijital Vitrini', max_length=200, null=True, verbose_name='slogan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_fa',
            field=models.CharField(default='QR Menunuz, Isletmenizin Dijital Vitrini', max_length=200, null=True, verbose_name='slogan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_tr',
            field=models.CharField(default='QR Menunuz, Isletmenizin Dijital Vitrini', max_length=200, null=True, verbose_name='slogan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_uk',
            field=models.CharField(default='QR Menunuz, Isletmenizin Dijital Vitrini', max_length=200, null=True, verbose_name='slogan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_message_ar',
            field=models.CharField(default='Merhaba! E-Menum hakkinda bilgi almak istiyorum.', max_length=300, null=True, verbose_name='WhatsApp mesaj'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_message_en',
            field=models.CharField(default='Merhaba! E-Menum hakkinda bilgi almak istiyorum.', max_length=300, null=True, verbose_name='WhatsApp mesaj'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_message_fa',
            field=models.CharField(default='Merhaba! E-Menum hakkinda bilgi almak istiyorum.', max_length=300, null=True, verbose_name='WhatsApp mesaj'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_message_tr',
            field=models.CharField(default='Merhaba! E-Menum hakkinda bilgi almak istiyorum.', max_length=300, null=True, verbose_name='WhatsApp mesaj'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_message_uk',
            field=models.CharField(default='Merhaba! E-Menum hakkinda bilgi almak istiyorum.', max_length=300, null=True, verbose_name='WhatsApp mesaj'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='ad soyad'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='ad soyad'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='ad soyad'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='ad soyad'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='ad soyad'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='unvan'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='unvan'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='unvan'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='unvan'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='unvan'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_location_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='konum'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_location_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='konum'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_location_fa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='konum'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_location_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='konum'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_location_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='konum'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='yazar adi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='yazar adi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='yazar adi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='yazar adi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='yazar adi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_role_or_business_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='rol / isletme'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_role_or_business_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='rol / isletme'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_role_or_business_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='rol / isletme'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_role_or_business_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='rol / isletme'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_role_or_business_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='rol / isletme'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='business_type_label_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='isletme tipi etiketi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='business_type_label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='isletme tipi etiketi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='business_type_label_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='isletme tipi etiketi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='business_type_label_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='isletme tipi etiketi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='business_type_label_uk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='isletme tipi etiketi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_ar',
            field=models.TextField(null=True, verbose_name='yorum'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_en',
            field=models.TextField(null=True, verbose_name='yorum'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_fa',
            field=models.TextField(null=True, verbose_name='yorum'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_tr',
            field=models.TextField(null=True, verbose_name='yorum'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_uk',
            field=models.TextField(null=True, verbose_name='yorum'),
        ),
        migrations.AddField(
            model_name='trustbadge',
            name='label_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='trustbadge',
            name='label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='trustbadge',
            name='label_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='trustbadge',
            name='label_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='trustbadge',
            name='label_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='trustlocation',
            name='text_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='metin'),
        ),
        migrations.AddField(
            model_name='trustlocation',
            name='text_en',
            field=models.CharField(max_length=200, null=True, verbose_name='metin'),
        ),
        migrations.AddField(
            model_name='trustlocation',
            name='text_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='metin'),
        ),
        migrations.AddField(
            model_name='trustlocation',
            name='text_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='metin'),
        ),
        migrations.AddField(
            model_name='trustlocation',
            name='text_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='metin'),
        ),
    ]
