# Generated by Django 5.2.11 on 2026-02-23 10:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_blogpost_category_ar_blogpost_category_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Canonical URL to prevent duplicate content",
                max_length=500,
                verbose_name="Canonical URL",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="focus_keyword",
            field=models.CharField(
                blank=True,
                help_text="Primary keyword to optimize for",
                max_length=100,
                verbose_name="Focus keyword",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="last_seo_analysis",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last SEO score calculation",
                null=True,
                verbose_name="Last SEO analysis",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated keywords",
                max_length=255,
                verbose_name="Meta keywords",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Page title for search engines (max 70 chars)",
                max_length=70,
                verbose_name="Meta title",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="Open Graph description for social sharing",
                max_length=200,
                verbose_name="OG description",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Open Graph image (recommended 1200x630)",
                null=True,
                upload_to="seo/og/",
                verbose_name="OG image",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="Open Graph title for social sharing",
                max_length=70,
                verbose_name="OG title",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="og_type",
            field=models.CharField(
                default="website",
                help_text="Open Graph type (e.g. website, article)",
                max_length=50,
                verbose_name="OG type",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="robots_extra",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Additional robots directives (e.g. noarchive, nosnippet)",
                verbose_name="Robots extra directives",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="robots_follow",
            field=models.BooleanField(
                default=True,
                help_text="Allow search engines to follow links on this page",
                verbose_name="Robots follow",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="robots_index",
            field=models.BooleanField(
                default=True,
                help_text="Allow search engines to index this page",
                verbose_name="Robots index",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="seo_score",
            field=models.IntegerField(
                default=0,
                help_text="Calculated SEO quality score (0-100)",
                verbose_name="SEO score",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="seo_suggestions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Auto-generated improvement suggestions",
                verbose_name="SEO suggestions",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="sitemap_changefreq",
            field=models.CharField(
                choices=[
                    ("always", "Always"),
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("never", "Never"),
                ],
                default="weekly",
                help_text="Expected page update frequency",
                max_length=10,
                verbose_name="Sitemap change frequency",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="sitemap_include",
            field=models.BooleanField(
                default=True,
                help_text="Whether to include this page in the XML sitemap",
                verbose_name="Include in sitemap",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="sitemap_priority",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.5"),
                help_text="Priority in sitemap (0.0 to 1.0)",
                max_digits=2,
                verbose_name="Sitemap priority",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="structured_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom JSON-LD structured data override",
                verbose_name="Structured data",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="twitter_card",
            field=models.CharField(
                choices=[
                    ("summary", "Summary"),
                    ("summary_large_image", "Summary Large Image"),
                    ("player", "Player"),
                    ("app", "App"),
                ],
                default="summary_large_image",
                help_text="Twitter Card display type",
                max_length=20,
                verbose_name="Twitter card",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="twitter_description",
            field=models.CharField(
                blank=True,
                help_text="Description for Twitter Card",
                max_length=200,
                verbose_name="Twitter description",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="twitter_image",
            field=models.ImageField(
                blank=True,
                help_text="Image for Twitter Card",
                null=True,
                upload_to="seo/twitter/",
                verbose_name="Twitter image",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="twitter_title",
            field=models.CharField(
                blank=True,
                help_text="Title for Twitter Card",
                max_length=70,
                verbose_name="Twitter title",
            ),
        ),
    ]
