# Generated by Django 5.2.11 on 2026-02-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_storefront_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandasset",
            name="description_ar",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="description_tr",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="title_ar",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="title_de",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="title_tr",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="benefits_ar",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="yan haklar",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="benefits_de",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="yan haklar",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="benefits_en",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="yan haklar",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="benefits_ru",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="yan haklar",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="benefits_tr",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="yan haklar",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="department_ar",
            field=models.CharField(max_length=100, null=True, verbose_name="departman"),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="department_de",
            field=models.CharField(max_length=100, null=True, verbose_name="departman"),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="department_en",
            field=models.CharField(max_length=100, null=True, verbose_name="departman"),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="department_ru",
            field=models.CharField(max_length=100, null=True, verbose_name="departman"),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="department_tr",
            field=models.CharField(max_length=100, null=True, verbose_name="departman"),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="description_ar",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="aciklama"
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="description_de",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="aciklama"
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="description_en",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="aciklama"
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="description_ru",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="aciklama"
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="description_tr",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="aciklama"
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="location_ar",
            field=models.CharField(
                default="Istanbul, Turkiye",
                max_length=100,
                null=True,
                verbose_name="konum",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="location_de",
            field=models.CharField(
                default="Istanbul, Turkiye",
                max_length=100,
                null=True,
                verbose_name="konum",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="location_en",
            field=models.CharField(
                default="Istanbul, Turkiye",
                max_length=100,
                null=True,
                verbose_name="konum",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="location_ru",
            field=models.CharField(
                default="Istanbul, Turkiye",
                max_length=100,
                null=True,
                verbose_name="konum",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="location_tr",
            field=models.CharField(
                default="Istanbul, Turkiye",
                max_length=100,
                null=True,
                verbose_name="konum",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="requirements_ar",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="gereksinimler",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="requirements_de",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="gereksinimler",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="requirements_en",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="gereksinimler",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="requirements_ru",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="gereksinimler",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="requirements_tr",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="gereksinimler",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="title_ar",
            field=models.CharField(max_length=200, null=True, verbose_name="pozisyon"),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="title_de",
            field=models.CharField(max_length=200, null=True, verbose_name="pozisyon"),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="pozisyon"),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="pozisyon"),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="title_tr",
            field=models.CharField(max_length=200, null=True, verbose_name="pozisyon"),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="challenge_ar",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="zorluk"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="challenge_de",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="zorluk"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="challenge_en",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="zorluk"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="challenge_ru",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="zorluk"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="challenge_tr",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="zorluk"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="excerpt_ar",
            field=models.TextField(
                blank=True,
                help_text="Kart onizlemesi (max 200 karakter)",
                null=True,
                verbose_name="ozet",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="excerpt_de",
            field=models.TextField(
                blank=True,
                help_text="Kart onizlemesi (max 200 karakter)",
                null=True,
                verbose_name="ozet",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="excerpt_en",
            field=models.TextField(
                blank=True,
                help_text="Kart onizlemesi (max 200 karakter)",
                null=True,
                verbose_name="ozet",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="excerpt_ru",
            field=models.TextField(
                blank=True,
                help_text="Kart onizlemesi (max 200 karakter)",
                null=True,
                verbose_name="ozet",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="excerpt_tr",
            field=models.TextField(
                blank=True,
                help_text="Kart onizlemesi (max 200 karakter)",
                null=True,
                verbose_name="ozet",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_ar",
            field=models.TextField(
                blank=True, null=True, verbose_name="musteri yorumu"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_author_ar",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="yorum sahibi"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_author_de",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="yorum sahibi"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_author_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="yorum sahibi"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_author_ru",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="yorum sahibi"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_author_title_ar",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="yorum sahibi unvani",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_author_title_de",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="yorum sahibi unvani",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_author_title_en",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="yorum sahibi unvani",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_author_title_ru",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="yorum sahibi unvani",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_author_title_tr",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="yorum sahibi unvani",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_author_tr",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="yorum sahibi"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_de",
            field=models.TextField(
                blank=True, null=True, verbose_name="musteri yorumu"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="musteri yorumu"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="musteri yorumu"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_tr",
            field=models.TextField(
                blank=True, null=True, verbose_name="musteri yorumu"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="results_ar",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="sonuclar"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="results_de",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="sonuclar"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="results_en",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="sonuclar"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="results_ru",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="sonuclar"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="results_tr",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="sonuclar"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="solution_ar",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="cozum"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="solution_de",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="cozum"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="solution_en",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="cozum"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="solution_ru",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="cozum"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="solution_tr",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="cozum"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_1_label_ar",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 1 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_1_label_de",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 1 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_1_label_en",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 1 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_1_label_ru",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 1 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_1_label_tr",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 1 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_2_label_ar",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 2 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_2_label_de",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 2 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_2_label_en",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 2 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_2_label_ru",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 2 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_2_label_tr",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 2 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_3_label_ar",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 3 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_3_label_de",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 3 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_3_label_en",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 3 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_3_label_ru",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 3 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_3_label_tr",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 3 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="title_ar",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="title_de",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="title_tr",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="freetool",
            name="description_ar",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="freetool",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="freetool",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="freetool",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="freetool",
            name="description_tr",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="freetool",
            name="title_ar",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="freetool",
            name="title_de",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="freetool",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="freetool",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="freetool",
            name="title_tr",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="content_ar",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="content_de",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="content_en",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="content_ru",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="content_tr",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="title_ar",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="title_de",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="title_en",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="title_ru",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="title_tr",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="description_ar",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="description_tr",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="name_ar",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="name_de",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="name_tr",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="content_ar",
            field=models.TextField(
                blank=True,
                help_text="Rapor tanitim sayfasi HTML",
                null=True,
                verbose_name="icerik",
            ),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="content_de",
            field=models.TextField(
                blank=True,
                help_text="Rapor tanitim sayfasi HTML",
                null=True,
                verbose_name="icerik",
            ),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="content_en",
            field=models.TextField(
                blank=True,
                help_text="Rapor tanitim sayfasi HTML",
                null=True,
                verbose_name="icerik",
            ),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="content_ru",
            field=models.TextField(
                blank=True,
                help_text="Rapor tanitim sayfasi HTML",
                null=True,
                verbose_name="icerik",
            ),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="content_tr",
            field=models.TextField(
                blank=True,
                help_text="Rapor tanitim sayfasi HTML",
                null=True,
                verbose_name="icerik",
            ),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="excerpt_ar",
            field=models.TextField(blank=True, null=True, verbose_name="ozet"),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="excerpt_de",
            field=models.TextField(blank=True, null=True, verbose_name="ozet"),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="excerpt_en",
            field=models.TextField(blank=True, null=True, verbose_name="ozet"),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="excerpt_ru",
            field=models.TextField(blank=True, null=True, verbose_name="ozet"),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="excerpt_tr",
            field=models.TextField(blank=True, null=True, verbose_name="ozet"),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="title_ar",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="title_de",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="title_tr",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="investorfinancial",
            name="metric_name_ar",
            field=models.CharField(
                max_length=100, null=True, verbose_name="metrik adi"
            ),
        ),
        migrations.AddField(
            model_name="investorfinancial",
            name="metric_name_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="metrik adi"
            ),
        ),
        migrations.AddField(
            model_name="investorfinancial",
            name="metric_name_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="metrik adi"
            ),
        ),
        migrations.AddField(
            model_name="investorfinancial",
            name="metric_name_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="metrik adi"
            ),
        ),
        migrations.AddField(
            model_name="investorfinancial",
            name="metric_name_tr",
            field=models.CharField(
                max_length=100, null=True, verbose_name="metrik adi"
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="investment_thesis_ar",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="yatirim tezi",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="investment_thesis_de",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="yatirim tezi",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="investment_thesis_en",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="yatirim tezi",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="investment_thesis_ru",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="yatirim tezi",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="investment_thesis_tr",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="yatirim tezi",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="overview_content_ar",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="genel bakis",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="overview_content_de",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="genel bakis",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="overview_content_en",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="genel bakis",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="overview_content_ru",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="genel bakis",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="overview_content_tr",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="genel bakis",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="subtitle_ar",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="subtitle_de",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="subtitle_en",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="subtitle_ru",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="subtitle_tr",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="title_ar",
            field=models.CharField(
                default="Yatirimci Iliskileri",
                max_length=200,
                null=True,
                verbose_name="baslik",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="title_de",
            field=models.CharField(
                default="Yatirimci Iliskileri",
                max_length=200,
                null=True,
                verbose_name="baslik",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="title_en",
            field=models.CharField(
                default="Yatirimci Iliskileri",
                max_length=200,
                null=True,
                verbose_name="baslik",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="title_ru",
            field=models.CharField(
                default="Yatirimci Iliskileri",
                max_length=200,
                null=True,
                verbose_name="baslik",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="title_tr",
            field=models.CharField(
                default="Yatirimci Iliskileri",
                max_length=200,
                null=True,
                verbose_name="baslik",
            ),
        ),
        migrations.AddField(
            model_name="investorpresentation",
            name="description_ar",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="investorpresentation",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="investorpresentation",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="investorpresentation",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="investorpresentation",
            name="description_tr",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="investorpresentation",
            name="title_ar",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="investorpresentation",
            name="title_de",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="investorpresentation",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="investorpresentation",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="investorpresentation",
            name="title_tr",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="description_ar",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="description_tr",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="title_ar",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="title_de",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="title_tr",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="partnerbenefit",
            name="text_ar",
            field=models.CharField(max_length=300, null=True, verbose_name="metin"),
        ),
        migrations.AddField(
            model_name="partnerbenefit",
            name="text_de",
            field=models.CharField(max_length=300, null=True, verbose_name="metin"),
        ),
        migrations.AddField(
            model_name="partnerbenefit",
            name="text_en",
            field=models.CharField(max_length=300, null=True, verbose_name="metin"),
        ),
        migrations.AddField(
            model_name="partnerbenefit",
            name="text_ru",
            field=models.CharField(max_length=300, null=True, verbose_name="metin"),
        ),
        migrations.AddField(
            model_name="partnerbenefit",
            name="text_tr",
            field=models.CharField(max_length=300, null=True, verbose_name="metin"),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="commission_info_ar",
            field=models.TextField(
                blank=True, null=True, verbose_name="komisyon bilgisi"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="commission_info_de",
            field=models.TextField(
                blank=True, null=True, verbose_name="komisyon bilgisi"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="commission_info_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="komisyon bilgisi"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="commission_info_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="komisyon bilgisi"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="commission_info_tr",
            field=models.TextField(
                blank=True, null=True, verbose_name="komisyon bilgisi"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="description_ar",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="aciklama"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="description_de",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="aciklama"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="description_en",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="aciklama"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="description_ru",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="aciklama"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="description_tr",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="aciklama"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="requirements_ar",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="katilim kosullari",
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="requirements_de",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="katilim kosullari",
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="requirements_en",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="katilim kosullari",
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="requirements_ru",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="katilim kosullari",
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="requirements_tr",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="katilim kosullari",
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="title_ar",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="title_de",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="title_tr",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="partnertier",
            name="description_ar",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="partnertier",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="partnertier",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="partnertier",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="partnertier",
            name="description_tr",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="partnertier",
            name="name_ar",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="partnertier",
            name="name_de",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="partnertier",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="partnertier",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="partnertier",
            name="name_tr",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="content_ar",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="content_de",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="content_en",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="content_ru",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="content_tr",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="excerpt_ar",
            field=models.TextField(blank=True, null=True, verbose_name="ozet"),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="excerpt_de",
            field=models.TextField(blank=True, null=True, verbose_name="ozet"),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="excerpt_en",
            field=models.TextField(blank=True, null=True, verbose_name="ozet"),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="excerpt_ru",
            field=models.TextField(blank=True, null=True, verbose_name="ozet"),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="excerpt_tr",
            field=models.TextField(blank=True, null=True, verbose_name="ozet"),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="title_ar",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="title_de",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="title_en",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="title_ru",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="title_tr",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="resourcecategory",
            name="name_ar",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="resourcecategory",
            name="name_de",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="resourcecategory",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="resourcecategory",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="resourcecategory",
            name="name_tr",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="roicalculatorconfig",
            name="description_ar",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="roicalculatorconfig",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="roicalculatorconfig",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="roicalculatorconfig",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="roicalculatorconfig",
            name="description_tr",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="roicalculatorconfig",
            name="title_ar",
            field=models.CharField(
                default="ROI Hesaplayici",
                max_length=200,
                null=True,
                verbose_name="baslik",
            ),
        ),
        migrations.AddField(
            model_name="roicalculatorconfig",
            name="title_de",
            field=models.CharField(
                default="ROI Hesaplayici",
                max_length=200,
                null=True,
                verbose_name="baslik",
            ),
        ),
        migrations.AddField(
            model_name="roicalculatorconfig",
            name="title_en",
            field=models.CharField(
                default="ROI Hesaplayici",
                max_length=200,
                null=True,
                verbose_name="baslik",
            ),
        ),
        migrations.AddField(
            model_name="roicalculatorconfig",
            name="title_ru",
            field=models.CharField(
                default="ROI Hesaplayici",
                max_length=200,
                null=True,
                verbose_name="baslik",
            ),
        ),
        migrations.AddField(
            model_name="roicalculatorconfig",
            name="title_tr",
            field=models.CharField(
                default="ROI Hesaplayici",
                max_length=200,
                null=True,
                verbose_name="baslik",
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="description_ar",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="sector",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="sector",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="sector",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="sector",
            name="description_tr",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="sector",
            name="name_ar",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="sector",
            name="name_de",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="sector",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="sector",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="sector",
            name="name_tr",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_text_ar",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="duyuru metni"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_text_de",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="duyuru metni"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_text_en",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="duyuru metni"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_text_ru",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="duyuru metni"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_text_tr",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="duyuru metni"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_text_ar",
            field=models.TextField(
                blank=True,
                default="Web sitemizde size daha iyi bir deneyim sunabilmek icin cerezleri kullaniyoruz.",
                null=True,
                verbose_name="cerez banner metni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_text_de",
            field=models.TextField(
                blank=True,
                default="Web sitemizde size daha iyi bir deneyim sunabilmek icin cerezleri kullaniyoruz.",
                null=True,
                verbose_name="cerez banner metni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_text_en",
            field=models.TextField(
                blank=True,
                default="Web sitemizde size daha iyi bir deneyim sunabilmek icin cerezleri kullaniyoruz.",
                null=True,
                verbose_name="cerez banner metni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_text_ru",
            field=models.TextField(
                blank=True,
                default="Web sitemizde size daha iyi bir deneyim sunabilmek icin cerezleri kullaniyoruz.",
                null=True,
                verbose_name="cerez banner metni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_text_tr",
            field=models.TextField(
                blank=True,
                default="Web sitemizde size daha iyi bir deneyim sunabilmek icin cerezleri kullaniyoruz.",
                null=True,
                verbose_name="cerez banner metni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_title_ar",
            field=models.CharField(
                default="Cerez Kullanimi",
                max_length=200,
                null=True,
                verbose_name="cerez banner basligi",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_title_de",
            field=models.CharField(
                default="Cerez Kullanimi",
                max_length=200,
                null=True,
                verbose_name="cerez banner basligi",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_title_en",
            field=models.CharField(
                default="Cerez Kullanimi",
                max_length=200,
                null=True,
                verbose_name="cerez banner basligi",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_title_ru",
            field=models.CharField(
                default="Cerez Kullanimi",
                max_length=200,
                null=True,
                verbose_name="cerez banner basligi",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_title_tr",
            field=models.CharField(
                default="Cerez Kullanimi",
                max_length=200,
                null=True,
                verbose_name="cerez banner basligi",
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="content_ar",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="content_de",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="content_en",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="content_ru",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="content_tr",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="key_benefits_ar",
            field=models.TextField(
                blank=True,
                help_text="HTML liste",
                null=True,
                verbose_name="temel faydalar",
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="key_benefits_de",
            field=models.TextField(
                blank=True,
                help_text="HTML liste",
                null=True,
                verbose_name="temel faydalar",
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="key_benefits_en",
            field=models.TextField(
                blank=True,
                help_text="HTML liste",
                null=True,
                verbose_name="temel faydalar",
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="key_benefits_ru",
            field=models.TextField(
                blank=True,
                help_text="HTML liste",
                null=True,
                verbose_name="temel faydalar",
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="key_benefits_tr",
            field=models.TextField(
                blank=True,
                help_text="HTML liste",
                null=True,
                verbose_name="temel faydalar",
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="pain_points_ar",
            field=models.TextField(
                blank=True, help_text="HTML liste", null=True, verbose_name="sorunlar"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="pain_points_de",
            field=models.TextField(
                blank=True, help_text="HTML liste", null=True, verbose_name="sorunlar"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="pain_points_en",
            field=models.TextField(
                blank=True, help_text="HTML liste", null=True, verbose_name="sorunlar"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="pain_points_ru",
            field=models.TextField(
                blank=True, help_text="HTML liste", null=True, verbose_name="sorunlar"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="pain_points_tr",
            field=models.TextField(
                blank=True, help_text="HTML liste", null=True, verbose_name="sorunlar"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="subtitle_ar",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="subtitle_de",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="subtitle_en",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="subtitle_ru",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="subtitle_tr",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="target_audience_ar",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="hedef kitle"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="target_audience_de",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="hedef kitle"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="target_audience_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="hedef kitle"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="target_audience_ru",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="hedef kitle"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="target_audience_tr",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="hedef kitle"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="title_ar",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="title_de",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="title_tr",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="webinar",
            name="description_ar",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="webinar",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="webinar",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="webinar",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="webinar",
            name="description_tr",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="webinar",
            name="title_ar",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="webinar",
            name="title_de",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="webinar",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="webinar",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="webinar",
            name="title_tr",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
    ]
