# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_plandisplayfeature_icon_svg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investorpage",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                default="investor@e-menum.net",
                max_length=254,
                verbose_name="iletisim e-posta",
            ),
        ),
        migrations.AlterField(
            model_name="partnerprogram",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                default="partners@e-menum.net",
                max_length=254,
                verbose_name="iletisim e-posta",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="email",
            field=models.EmailField(
                default="info@e-menum.net",
                max_length=254,
                verbose_name="e-posta",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="status_page_url",
            field=models.URLField(
                blank=True,
                default="https://status.e-menum.net",
                verbose_name="durum sayfasi URL",
            ),
        ),
    ]
