# Generated by Django 5.2.12 on 2026-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_alter_sitesettings_status_page_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="category_de",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="category_ru",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="content_de",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="content_ru",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="excerpt_de",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="excerpt_ru",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="meta_description_de",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="meta_description_ru",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="brandasset",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="brandasset",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="brandasset",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="brandasset",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="careerposition",
            name="benefits_de",
        ),
        migrations.RemoveField(
            model_name="careerposition",
            name="benefits_ru",
        ),
        migrations.RemoveField(
            model_name="careerposition",
            name="department_de",
        ),
        migrations.RemoveField(
            model_name="careerposition",
            name="department_ru",
        ),
        migrations.RemoveField(
            model_name="careerposition",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="careerposition",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="careerposition",
            name="location_de",
        ),
        migrations.RemoveField(
            model_name="careerposition",
            name="location_ru",
        ),
        migrations.RemoveField(
            model_name="careerposition",
            name="requirements_de",
        ),
        migrations.RemoveField(
            model_name="careerposition",
            name="requirements_ru",
        ),
        migrations.RemoveField(
            model_name="careerposition",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="careerposition",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="challenge_de",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="challenge_ru",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="excerpt_de",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="excerpt_ru",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="quote_author_de",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="quote_author_ru",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="quote_author_title_de",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="quote_author_title_ru",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="quote_de",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="quote_ru",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="results_de",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="results_ru",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="solution_de",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="solution_ru",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="stat_1_label_de",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="stat_1_label_ru",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="stat_2_label_de",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="stat_2_label_ru",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="stat_3_label_de",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="stat_3_label_ru",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="companystat",
            name="label_de",
        ),
        migrations.RemoveField(
            model_name="companystat",
            name="label_ru",
        ),
        migrations.RemoveField(
            model_name="companystat",
            name="value_de",
        ),
        migrations.RemoveField(
            model_name="companystat",
            name="value_ru",
        ),
        migrations.RemoveField(
            model_name="companyvalue",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="companyvalue",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="companyvalue",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="companyvalue",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_de",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_ru",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_de",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_ru",
        ),
        migrations.RemoveField(
            model_name="featurebullet",
            name="text_de",
        ),
        migrations.RemoveField(
            model_name="featurebullet",
            name="text_ru",
        ),
        migrations.RemoveField(
            model_name="featurecategory",
            name="badge_text_de",
        ),
        migrations.RemoveField(
            model_name="featurecategory",
            name="badge_text_ru",
        ),
        migrations.RemoveField(
            model_name="featurecategory",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="featurecategory",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="featurecategory",
            name="image_alt_de",
        ),
        migrations.RemoveField(
            model_name="featurecategory",
            name="image_alt_ru",
        ),
        migrations.RemoveField(
            model_name="featurecategory",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="featurecategory",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="freetool",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="freetool",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="freetool",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="freetool",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="helparticle",
            name="content_de",
        ),
        migrations.RemoveField(
            model_name="helparticle",
            name="content_ru",
        ),
        migrations.RemoveField(
            model_name="helparticle",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="helparticle",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="helpcategory",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="helpcategory",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="helpcategory",
            name="name_de",
        ),
        migrations.RemoveField(
            model_name="helpcategory",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="homesection",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="homesection",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="homesection",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="homesection",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="industryreport",
            name="content_de",
        ),
        migrations.RemoveField(
            model_name="industryreport",
            name="content_ru",
        ),
        migrations.RemoveField(
            model_name="industryreport",
            name="excerpt_de",
        ),
        migrations.RemoveField(
            model_name="industryreport",
            name="excerpt_ru",
        ),
        migrations.RemoveField(
            model_name="industryreport",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="industryreport",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="investorfinancial",
            name="metric_name_de",
        ),
        migrations.RemoveField(
            model_name="investorfinancial",
            name="metric_name_ru",
        ),
        migrations.RemoveField(
            model_name="investorpage",
            name="investment_thesis_de",
        ),
        migrations.RemoveField(
            model_name="investorpage",
            name="investment_thesis_ru",
        ),
        migrations.RemoveField(
            model_name="investorpage",
            name="overview_content_de",
        ),
        migrations.RemoveField(
            model_name="investorpage",
            name="overview_content_ru",
        ),
        migrations.RemoveField(
            model_name="investorpage",
            name="subtitle_de",
        ),
        migrations.RemoveField(
            model_name="investorpage",
            name="subtitle_ru",
        ),
        migrations.RemoveField(
            model_name="investorpage",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="investorpage",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="investorpresentation",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="investorpresentation",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="investorpresentation",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="investorpresentation",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="legalpage",
            name="content_de",
        ),
        migrations.RemoveField(
            model_name="legalpage",
            name="content_ru",
        ),
        migrations.RemoveField(
            model_name="legalpage",
            name="last_updated_display_de",
        ),
        migrations.RemoveField(
            model_name="legalpage",
            name="last_updated_display_ru",
        ),
        migrations.RemoveField(
            model_name="legalpage",
            name="meta_description_de",
        ),
        migrations.RemoveField(
            model_name="legalpage",
            name="meta_description_ru",
        ),
        migrations.RemoveField(
            model_name="legalpage",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="legalpage",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="navigationlink",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="navigationlink",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="navigationlink",
            name="label_de",
        ),
        migrations.RemoveField(
            model_name="navigationlink",
            name="label_ru",
        ),
        migrations.RemoveField(
            model_name="pagehero",
            name="badge_text_de",
        ),
        migrations.RemoveField(
            model_name="pagehero",
            name="badge_text_ru",
        ),
        migrations.RemoveField(
            model_name="pagehero",
            name="cta_primary_text_de",
        ),
        migrations.RemoveField(
            model_name="pagehero",
            name="cta_primary_text_ru",
        ),
        migrations.RemoveField(
            model_name="pagehero",
            name="cta_secondary_text_de",
        ),
        migrations.RemoveField(
            model_name="pagehero",
            name="cta_secondary_text_ru",
        ),
        migrations.RemoveField(
            model_name="pagehero",
            name="subtitle_de",
        ),
        migrations.RemoveField(
            model_name="pagehero",
            name="subtitle_ru",
        ),
        migrations.RemoveField(
            model_name="pagehero",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="pagehero",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="pagehero",
            name="trust_text_de",
        ),
        migrations.RemoveField(
            model_name="pagehero",
            name="trust_text_ru",
        ),
        migrations.RemoveField(
            model_name="partnerbenefit",
            name="text_de",
        ),
        migrations.RemoveField(
            model_name="partnerbenefit",
            name="text_ru",
        ),
        migrations.RemoveField(
            model_name="partnerprogram",
            name="commission_info_de",
        ),
        migrations.RemoveField(
            model_name="partnerprogram",
            name="commission_info_ru",
        ),
        migrations.RemoveField(
            model_name="partnerprogram",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="partnerprogram",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="partnerprogram",
            name="requirements_de",
        ),
        migrations.RemoveField(
            model_name="partnerprogram",
            name="requirements_ru",
        ),
        migrations.RemoveField(
            model_name="partnerprogram",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="partnerprogram",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="partnertier",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="partnertier",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="partnertier",
            name="name_de",
        ),
        migrations.RemoveField(
            model_name="partnertier",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="plandisplayfeature",
            name="text_de",
        ),
        migrations.RemoveField(
            model_name="plandisplayfeature",
            name="text_ru",
        ),
        migrations.RemoveField(
            model_name="pressrelease",
            name="content_de",
        ),
        migrations.RemoveField(
            model_name="pressrelease",
            name="content_ru",
        ),
        migrations.RemoveField(
            model_name="pressrelease",
            name="excerpt_de",
        ),
        migrations.RemoveField(
            model_name="pressrelease",
            name="excerpt_ru",
        ),
        migrations.RemoveField(
            model_name="pressrelease",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="pressrelease",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="resourcecategory",
            name="name_de",
        ),
        migrations.RemoveField(
            model_name="resourcecategory",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="roicalculatorconfig",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="roicalculatorconfig",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="roicalculatorconfig",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="roicalculatorconfig",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="name_de",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="address_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="address_ru",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="announcement_text_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="announcement_text_ru",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="company_name_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="company_name_ru",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cookie_banner_text_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cookie_banner_text_ru",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cookie_banner_title_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cookie_banner_title_ru",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cta_primary_text_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cta_primary_text_ru",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cta_secondary_text_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cta_secondary_text_ru",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cta_trust_text_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cta_trust_text_ru",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="tagline_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="tagline_ru",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="whatsapp_message_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="whatsapp_message_ru",
        ),
        migrations.RemoveField(
            model_name="solutionpage",
            name="content_de",
        ),
        migrations.RemoveField(
            model_name="solutionpage",
            name="content_ru",
        ),
        migrations.RemoveField(
            model_name="solutionpage",
            name="key_benefits_de",
        ),
        migrations.RemoveField(
            model_name="solutionpage",
            name="key_benefits_ru",
        ),
        migrations.RemoveField(
            model_name="solutionpage",
            name="pain_points_de",
        ),
        migrations.RemoveField(
            model_name="solutionpage",
            name="pain_points_ru",
        ),
        migrations.RemoveField(
            model_name="solutionpage",
            name="subtitle_de",
        ),
        migrations.RemoveField(
            model_name="solutionpage",
            name="subtitle_ru",
        ),
        migrations.RemoveField(
            model_name="solutionpage",
            name="target_audience_de",
        ),
        migrations.RemoveField(
            model_name="solutionpage",
            name="target_audience_ru",
        ),
        migrations.RemoveField(
            model_name="solutionpage",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="solutionpage",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="name_de",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="author_location_de",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="author_location_ru",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="author_name_de",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="author_name_ru",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="author_role_or_business_de",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="author_role_or_business_ru",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="business_type_label_de",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="business_type_label_ru",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="quote_de",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="quote_ru",
        ),
        migrations.RemoveField(
            model_name="trustbadge",
            name="label_de",
        ),
        migrations.RemoveField(
            model_name="trustbadge",
            name="label_ru",
        ),
        migrations.RemoveField(
            model_name="trustlocation",
            name="text_de",
        ),
        migrations.RemoveField(
            model_name="trustlocation",
            name="text_ru",
        ),
        migrations.RemoveField(
            model_name="webinar",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="webinar",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="webinar",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="webinar",
            name="title_ru",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="category_fa",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="kategori"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="category_uk",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="kategori"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_fa",
            field=models.TextField(
                help_text="HTML icerik desteklenir", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_uk",
            field=models.TextField(
                help_text="HTML icerik desteklenir", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="excerpt_fa",
            field=models.TextField(
                blank=True,
                help_text="Kart onizlemesinde gosterilir",
                null=True,
                verbose_name="ozet",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="excerpt_uk",
            field=models.TextField(
                blank=True,
                help_text="Kart onizlemesinde gosterilir",
                null=True,
                verbose_name="ozet",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_description_fa",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="meta aciklama"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_description_uk",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="meta aciklama"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_fa",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_uk",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="description_fa",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="benefits_fa",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="yan haklar",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="benefits_uk",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="yan haklar",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="department_fa",
            field=models.CharField(max_length=100, null=True, verbose_name="departman"),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="department_uk",
            field=models.CharField(max_length=100, null=True, verbose_name="departman"),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="description_fa",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="aciklama"
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="description_uk",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="aciklama"
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="location_fa",
            field=models.CharField(
                default="Istanbul, Turkiye",
                max_length=100,
                null=True,
                verbose_name="konum",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="location_uk",
            field=models.CharField(
                default="Istanbul, Turkiye",
                max_length=100,
                null=True,
                verbose_name="konum",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="requirements_fa",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="gereksinimler",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="requirements_uk",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="gereksinimler",
            ),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="pozisyon"),
        ),
        migrations.AddField(
            model_name="careerposition",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="pozisyon"),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="challenge_fa",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="zorluk"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="challenge_uk",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="zorluk"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="excerpt_fa",
            field=models.TextField(
                blank=True,
                help_text="Kart onizlemesi (max 200 karakter)",
                null=True,
                verbose_name="ozet",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="excerpt_uk",
            field=models.TextField(
                blank=True,
                help_text="Kart onizlemesi (max 200 karakter)",
                null=True,
                verbose_name="ozet",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_author_fa",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="yorum sahibi"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_author_title_fa",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="yorum sahibi unvani",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_author_title_uk",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="yorum sahibi unvani",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_author_uk",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="yorum sahibi"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_fa",
            field=models.TextField(
                blank=True, null=True, verbose_name="musteri yorumu"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="quote_uk",
            field=models.TextField(
                blank=True, null=True, verbose_name="musteri yorumu"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="results_fa",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="sonuclar"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="results_uk",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="sonuclar"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="solution_fa",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="cozum"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="solution_uk",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="cozum"
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_1_label_fa",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 1 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_1_label_uk",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 1 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_2_label_fa",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 2 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_2_label_uk",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 2 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_3_label_fa",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 3 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="stat_3_label_uk",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="istatistik 3 etiket",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="companystat",
            name="label_fa",
            field=models.CharField(max_length=100, null=True, verbose_name="etiket"),
        ),
        migrations.AddField(
            model_name="companystat",
            name="label_uk",
            field=models.CharField(max_length=100, null=True, verbose_name="etiket"),
        ),
        migrations.AddField(
            model_name="companystat",
            name="value_fa",
            field=models.CharField(max_length=50, null=True, verbose_name="deger"),
        ),
        migrations.AddField(
            model_name="companystat",
            name="value_uk",
            field=models.CharField(max_length=50, null=True, verbose_name="deger"),
        ),
        migrations.AddField(
            model_name="companyvalue",
            name="description_fa",
            field=models.TextField(null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="companyvalue",
            name="description_uk",
            field=models.TextField(null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="companyvalue",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="companyvalue",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_fa",
            field=models.TextField(null=True, verbose_name="cevap"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_uk",
            field=models.TextField(null=True, verbose_name="cevap"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_fa",
            field=models.CharField(max_length=300, null=True, verbose_name="soru"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_uk",
            field=models.CharField(max_length=300, null=True, verbose_name="soru"),
        ),
        migrations.AddField(
            model_name="featurebullet",
            name="text_fa",
            field=models.CharField(max_length=300, null=True, verbose_name="metin"),
        ),
        migrations.AddField(
            model_name="featurebullet",
            name="text_uk",
            field=models.CharField(max_length=300, null=True, verbose_name="metin"),
        ),
        migrations.AddField(
            model_name="featurecategory",
            name="badge_text_fa",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="badge metni"
            ),
        ),
        migrations.AddField(
            model_name="featurecategory",
            name="badge_text_uk",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="badge metni"
            ),
        ),
        migrations.AddField(
            model_name="featurecategory",
            name="description_fa",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="featurecategory",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="featurecategory",
            name="image_alt_fa",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="gorsel alt metni"
            ),
        ),
        migrations.AddField(
            model_name="featurecategory",
            name="image_alt_uk",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="gorsel alt metni"
            ),
        ),
        migrations.AddField(
            model_name="featurecategory",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="featurecategory",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="freetool",
            name="description_fa",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="freetool",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="freetool",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="freetool",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="content_fa",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="content_uk",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="title_fa",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="title_uk",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="description_fa",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="name_fa",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="name_uk",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="homesection",
            name="description_fa",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="homesection",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="homesection",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="homesection",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="content_fa",
            field=models.TextField(
                blank=True,
                help_text="Rapor tanitim sayfasi HTML",
                null=True,
                verbose_name="icerik",
            ),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="content_uk",
            field=models.TextField(
                blank=True,
                help_text="Rapor tanitim sayfasi HTML",
                null=True,
                verbose_name="icerik",
            ),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="excerpt_fa",
            field=models.TextField(blank=True, null=True, verbose_name="ozet"),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="excerpt_uk",
            field=models.TextField(blank=True, null=True, verbose_name="ozet"),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="industryreport",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="investorfinancial",
            name="metric_name_fa",
            field=models.CharField(
                max_length=100, null=True, verbose_name="metrik adi"
            ),
        ),
        migrations.AddField(
            model_name="investorfinancial",
            name="metric_name_uk",
            field=models.CharField(
                max_length=100, null=True, verbose_name="metrik adi"
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="investment_thesis_fa",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="yatirim tezi",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="investment_thesis_uk",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="yatirim tezi",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="overview_content_fa",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="genel bakis",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="overview_content_uk",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="genel bakis",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="subtitle_fa",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="subtitle_uk",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="title_fa",
            field=models.CharField(
                default="Yatirimci Iliskileri",
                max_length=200,
                null=True,
                verbose_name="baslik",
            ),
        ),
        migrations.AddField(
            model_name="investorpage",
            name="title_uk",
            field=models.CharField(
                default="Yatirimci Iliskileri",
                max_length=200,
                null=True,
                verbose_name="baslik",
            ),
        ),
        migrations.AddField(
            model_name="investorpresentation",
            name="description_fa",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="investorpresentation",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="investorpresentation",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="investorpresentation",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="legalpage",
            name="content_fa",
            field=models.TextField(
                help_text="HTML icerik desteklenir", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="legalpage",
            name="content_uk",
            field=models.TextField(
                help_text="HTML icerik desteklenir", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="legalpage",
            name="last_updated_display_fa",
            field=models.CharField(
                blank=True,
                help_text="Sayfada gosterilecek tarih metni",
                max_length=50,
                null=True,
                verbose_name="son guncelleme (gorunum)",
            ),
        ),
        migrations.AddField(
            model_name="legalpage",
            name="last_updated_display_uk",
            field=models.CharField(
                blank=True,
                help_text="Sayfada gosterilecek tarih metni",
                max_length=50,
                null=True,
                verbose_name="son guncelleme (gorunum)",
            ),
        ),
        migrations.AddField(
            model_name="legalpage",
            name="meta_description_fa",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="meta aciklama"
            ),
        ),
        migrations.AddField(
            model_name="legalpage",
            name="meta_description_uk",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="meta aciklama"
            ),
        ),
        migrations.AddField(
            model_name="legalpage",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="legalpage",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="description_fa",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="navigationlink",
            name="description_fa",
            field=models.CharField(
                blank=True,
                help_text="Dropdown aciklama metni",
                max_length=200,
                null=True,
                verbose_name="aciklama",
            ),
        ),
        migrations.AddField(
            model_name="navigationlink",
            name="description_uk",
            field=models.CharField(
                blank=True,
                help_text="Dropdown aciklama metni",
                max_length=200,
                null=True,
                verbose_name="aciklama",
            ),
        ),
        migrations.AddField(
            model_name="navigationlink",
            name="label_fa",
            field=models.CharField(max_length=100, null=True, verbose_name="etiket"),
        ),
        migrations.AddField(
            model_name="navigationlink",
            name="label_uk",
            field=models.CharField(max_length=100, null=True, verbose_name="etiket"),
        ),
        migrations.AddField(
            model_name="pagehero",
            name="badge_text_fa",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="badge metni"
            ),
        ),
        migrations.AddField(
            model_name="pagehero",
            name="badge_text_uk",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="badge metni"
            ),
        ),
        migrations.AddField(
            model_name="pagehero",
            name="cta_primary_text_fa",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="birincil CTA"
            ),
        ),
        migrations.AddField(
            model_name="pagehero",
            name="cta_primary_text_uk",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="birincil CTA"
            ),
        ),
        migrations.AddField(
            model_name="pagehero",
            name="cta_secondary_text_fa",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ikincil CTA"
            ),
        ),
        migrations.AddField(
            model_name="pagehero",
            name="cta_secondary_text_uk",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ikincil CTA"
            ),
        ),
        migrations.AddField(
            model_name="pagehero",
            name="subtitle_fa",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="pagehero",
            name="subtitle_uk",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="pagehero",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="pagehero",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="pagehero",
            name="trust_text_fa",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="guven metni"
            ),
        ),
        migrations.AddField(
            model_name="pagehero",
            name="trust_text_uk",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="guven metni"
            ),
        ),
        migrations.AddField(
            model_name="partnerbenefit",
            name="text_fa",
            field=models.CharField(max_length=300, null=True, verbose_name="metin"),
        ),
        migrations.AddField(
            model_name="partnerbenefit",
            name="text_uk",
            field=models.CharField(max_length=300, null=True, verbose_name="metin"),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="commission_info_fa",
            field=models.TextField(
                blank=True, null=True, verbose_name="komisyon bilgisi"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="commission_info_uk",
            field=models.TextField(
                blank=True, null=True, verbose_name="komisyon bilgisi"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="description_fa",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="aciklama"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="description_uk",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="aciklama"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="requirements_fa",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="katilim kosullari",
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="requirements_uk",
            field=models.TextField(
                blank=True,
                help_text="HTML icerik",
                null=True,
                verbose_name="katilim kosullari",
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="partnertier",
            name="description_fa",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="partnertier",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="partnertier",
            name="name_fa",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="partnertier",
            name="name_uk",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="plandisplayfeature",
            name="text_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="metin"),
        ),
        migrations.AddField(
            model_name="plandisplayfeature",
            name="text_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="metin"),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="content_fa",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="content_uk",
            field=models.TextField(
                help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="excerpt_fa",
            field=models.TextField(blank=True, null=True, verbose_name="ozet"),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="excerpt_uk",
            field=models.TextField(blank=True, null=True, verbose_name="ozet"),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="title_fa",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="pressrelease",
            name="title_uk",
            field=models.CharField(max_length=300, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="resourcecategory",
            name="name_fa",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="resourcecategory",
            name="name_uk",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="roicalculatorconfig",
            name="description_fa",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="roicalculatorconfig",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="roicalculatorconfig",
            name="title_fa",
            field=models.CharField(
                default="ROI Hesaplayici",
                max_length=200,
                null=True,
                verbose_name="baslik",
            ),
        ),
        migrations.AddField(
            model_name="roicalculatorconfig",
            name="title_uk",
            field=models.CharField(
                default="ROI Hesaplayici",
                max_length=200,
                null=True,
                verbose_name="baslik",
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="description_fa",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="sector",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="sector",
            name="name_fa",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="sector",
            name="name_uk",
            field=models.CharField(max_length=100, null=True, verbose_name="ad"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_fa",
            field=models.CharField(
                default="Istanbul, Turkiye",
                max_length=200,
                null=True,
                verbose_name="adres",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_uk",
            field=models.CharField(
                default="Istanbul, Turkiye",
                max_length=200,
                null=True,
                verbose_name="adres",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_text_fa",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="duyuru metni"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_text_uk",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="duyuru metni"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="company_name_fa",
            field=models.CharField(
                default="E-Menum", max_length=100, null=True, verbose_name="sirket adi"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="company_name_uk",
            field=models.CharField(
                default="E-Menum", max_length=100, null=True, verbose_name="sirket adi"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_text_fa",
            field=models.TextField(
                blank=True,
                default="Web sitemizde size daha iyi bir deneyim sunabilmek icin cerezleri kullaniyoruz.",
                null=True,
                verbose_name="cerez banner metni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_text_uk",
            field=models.TextField(
                blank=True,
                default="Web sitemizde size daha iyi bir deneyim sunabilmek icin cerezleri kullaniyoruz.",
                null=True,
                verbose_name="cerez banner metni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_title_fa",
            field=models.CharField(
                default="Cerez Kullanimi",
                max_length=200,
                null=True,
                verbose_name="cerez banner basligi",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_title_uk",
            field=models.CharField(
                default="Cerez Kullanimi",
                max_length=200,
                null=True,
                verbose_name="cerez banner basligi",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_primary_text_fa",
            field=models.CharField(
                default="14 Gun Ucretsiz Basla",
                max_length=100,
                null=True,
                verbose_name="birincil CTA metni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_primary_text_uk",
            field=models.CharField(
                default="14 Gun Ucretsiz Basla",
                max_length=100,
                null=True,
                verbose_name="birincil CTA metni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_secondary_text_fa",
            field=models.CharField(
                default="Demo Iste",
                max_length=100,
                null=True,
                verbose_name="ikincil CTA metni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_secondary_text_uk",
            field=models.CharField(
                default="Demo Iste",
                max_length=100,
                null=True,
                verbose_name="ikincil CTA metni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_trust_text_fa",
            field=models.CharField(
                default="Kredi karti gerekmez · 2 dakikada kurulum",
                max_length=200,
                null=True,
                verbose_name="guven metni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_trust_text_uk",
            field=models.CharField(
                default="Kredi karti gerekmez · 2 dakikada kurulum",
                max_length=200,
                null=True,
                verbose_name="guven metni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="description_fa",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tagline_fa",
            field=models.CharField(
                default="QR Menunuz, Isletmenizin Dijital Vitrini",
                max_length=200,
                null=True,
                verbose_name="slogan",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tagline_uk",
            field=models.CharField(
                default="QR Menunuz, Isletmenizin Dijital Vitrini",
                max_length=200,
                null=True,
                verbose_name="slogan",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_message_fa",
            field=models.CharField(
                default="Merhaba! E-Menum hakkinda bilgi almak istiyorum.",
                max_length=300,
                null=True,
                verbose_name="WhatsApp mesaj",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_message_uk",
            field=models.CharField(
                default="Merhaba! E-Menum hakkinda bilgi almak istiyorum.",
                max_length=300,
                null=True,
                verbose_name="WhatsApp mesaj",
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="content_fa",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="content_uk",
            field=models.TextField(
                blank=True, help_text="HTML icerik", null=True, verbose_name="icerik"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="key_benefits_fa",
            field=models.TextField(
                blank=True,
                help_text="HTML liste",
                null=True,
                verbose_name="temel faydalar",
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="key_benefits_uk",
            field=models.TextField(
                blank=True,
                help_text="HTML liste",
                null=True,
                verbose_name="temel faydalar",
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="pain_points_fa",
            field=models.TextField(
                blank=True, help_text="HTML liste", null=True, verbose_name="sorunlar"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="pain_points_uk",
            field=models.TextField(
                blank=True, help_text="HTML liste", null=True, verbose_name="sorunlar"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="subtitle_fa",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="subtitle_uk",
            field=models.TextField(blank=True, null=True, verbose_name="alt baslik"),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="target_audience_fa",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="hedef kitle"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="target_audience_uk",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="hedef kitle"
            ),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="name_fa",
            field=models.CharField(max_length=100, null=True, verbose_name="ad soyad"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="name_uk",
            field=models.CharField(max_length=100, null=True, verbose_name="ad soyad"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="unvan"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="unvan"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="author_location_fa",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="konum"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="author_location_uk",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="konum"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="author_name_fa",
            field=models.CharField(max_length=100, null=True, verbose_name="yazar adi"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="author_name_uk",
            field=models.CharField(max_length=100, null=True, verbose_name="yazar adi"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="author_role_or_business_fa",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="rol / isletme"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="author_role_or_business_uk",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="rol / isletme"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="business_type_label_fa",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="isletme tipi etiketi",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="business_type_label_uk",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="isletme tipi etiketi",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="quote_fa",
            field=models.TextField(null=True, verbose_name="yorum"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="quote_uk",
            field=models.TextField(null=True, verbose_name="yorum"),
        ),
        migrations.AddField(
            model_name="trustbadge",
            name="label_fa",
            field=models.CharField(max_length=100, null=True, verbose_name="etiket"),
        ),
        migrations.AddField(
            model_name="trustbadge",
            name="label_uk",
            field=models.CharField(max_length=100, null=True, verbose_name="etiket"),
        ),
        migrations.AddField(
            model_name="trustlocation",
            name="text_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="metin"),
        ),
        migrations.AddField(
            model_name="trustlocation",
            name="text_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="metin"),
        ),
        migrations.AddField(
            model_name="webinar",
            name="description_fa",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="webinar",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="aciklama"),
        ),
        migrations.AddField(
            model_name="webinar",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
        migrations.AddField(
            model_name="webinar",
            name="title_uk",
            field=models.CharField(max_length=200, null=True, verbose_name="baslik"),
        ),
    ]
